Handling Missing Data/imputation:

Handling Categorical Data/encoding:

Scaling Numerical Features:

Feature Engineering:

Handling Outliers:

Splitting Data:

Applying Dimensionality Reduction (if needed):

Validation:

Final Preprocessing Steps:

**Demographics**

Identification

id: Unique identifier for the loan application

member_id: Member identifier

**Personal Information**

emp_title: Employment title of the applicant

emp_length: Length of employment in years

home_ownership: Home ownership status

**Income and Verification**

annual_inc: Applicant's annual income

annual_inc_joint: Joint applicant's annual income

verification_status: Verification status of the applicant

verification_status_joint: Verification status of the joint applicant

**Financial Health **

Debt-to-Income

dti: Debt-to-Income ratio

dti_joint: Joint Debt-to-Income ratio

**Current Balances**

tot_coll_amt: Total collection amounts

tot_cur_bal: Total current balance of all accounts

total_bal_il: Total balance on installment loans

total_bal_ex_mort: Total balance excluding mortgage

total_bc_limit: Total bank card limit

total_il_high_credit_limit: Total installment loan high credit limit

**Credit Utilization**

revol_bal: Revolving balance

revol_util: Revolving line utilization rate

all_util: Balance to credit limit on all trades

total_rev_hi_lim: Total revolving high credit/credit limit

avg_cur_bal: Average current balance of all accounts

bc_open_to_buy: Bankcard open to buy

bc_util: Bankcard utilization rate

**Loan Details**
Loan Amount and Terms

loan_amnt: Loan amount

funded_amnt: Funded amount

funded_amnt_inv: Funded amount by investors

term: Loan term

int_rate: Interest rate

installment: Loan installment

**Loan Characteristics**

grade: Loan grade

sub_grade: Loan sub-grade

issue_d: Loan issue date

loan_status: Loan status

pymnt_plan: Payment plan indicator

purpose: Purpose of the loan

title: Loan title

zip_code: Zip code of the applicant

addr_state: State of the applicant

desc: Loan description

url: URL of the loan listing

loan_limit: Loan limit

loan_type: Type of loan applied for

loan_purpose: Purpose of the loan

loan_amount: Amount of loan requested

rate_of_interest: Interest rate applicable to the loan

interest_type: Indicates if the interest is fixed or variable

loan_term: Term of the loan in months

**Property and Occupancy **

property_value: Estimated value of the property

occupancy_type: Type of occupancy (e.g., primary, secondary residence)

total_units: Number of units the property has

**Credit Information**

Credit History

earliest_cr_line: Date of the earliest credit line

inq_last_6mths: Inquiries in the last 6 months

open_acc: Number of open accounts

pub_rec: Number of derogatory public records

total_acc: Total number of accounts

delinq_2yrs: Number of 30+ days past-due incidences in the borrower's credit file for the past 2 years

collections_12_mths_ex_med: Number of collections in the last 12 months
excluding medical collections

acc_now_delinq: Number of accounts currently delinquent

**Credit Utilization and Performance**

revol_bal: Revolving balance

revol_util: Revolving line utilization rate

total_rev_hi_lim: Total revolving high credit/credit limit

avg_cur_bal: Average current balance of all accounts

bc_open_to_buy: Bankcard open to buy

bc_util: Bankcard utilization rate

credit_worthiness: Categorization of the applicant's credit worthiness

open_credit: Indicates if the applicant has open credit lines

credit_type: Type of credit report used

credit_score: Applicant's credit score

co_applicant_credit_type: Credit report type for co-applicant

**Payment Information**

Payments and Recoveries

out_prncp: Remaining outstanding principal for total amount funded

out_prncp_inv: Remaining outstanding principal for portion of total amount funded by investors

total_pymnt: Payments received to date

total_pymnt_inv: Payments received to date for portion of total amount funded by investors

total_rec_prncp: Principal received to date

total_rec_int: Interest received to date

total_rec_late_fee: Late fees received to date

recoveries: Post charge off gross recovery

collection_recovery_fee: Collection recovery fee

last_pymnt_d: Last payment date

last_pymnt_amnt: Last payment amount

next_pymnt_d: Next payment date

last_credit_pull_d: The most recent date the applicant's credit was pulled

**Hardship and Settlement**

Hardship Information

hardship_flag: Hardship flag

hardship_type: Hardship type

hardship_reason: Hardship reason

hardship_status: Hardship status

deferral_term: Deferral term

hardship_amount: Hardship amount

hardship_start_date: Hardship start date

hardship_end_date: Hardship end date

payment_plan_start_date: Payment plan start date

hardship_length: Hardship length

hardship_dpd: Hardship days past due

hardship_loan_status: Hardship loan status

orig_projected_additional_accrued_interest: Original projected additional accrued interest

hardship_payoff_balance_amount: Hardship payoff balance amount

hardship_last_payment_amount: Hardship last payment amount

**Settlement Information **

debt_settlement_flag: Debt settlement flag

debt_settlement_flag_date: Debt settlement flag date

settlement_status: Settlement status

settlement_date: Settlement date

settlement_amount: Settlement amount

settlement_percentage: Settlement percentage

settlement_term: Settlement term


**Other Details**
Application and Loan Type

business_or_commercial: Whether the loan is for business or commercial purposes
submission_of_application: Whether the application was submitted to the institution directly or not

region: Geographic region of the applicant

security_type: Type of security provided for the loan

status: Indicates the loan status (e.g., default, non-default)
Recent Activity and Derogatory Marks

mths_since_last_delinq: Months since the last delinquency

mths_since_last_record: Months since the last public record

mths_since_last_major_derog: Months since last major derogatory
(derogatory: negative to lenders, and can include late payments, collection accounts, bankruptcy, charge-offs and other negative marks on credit report)

policy_code: Publicly available policy code for the specific loan

application_type: Indicates whether the loan is an individual application or a joint application

acc_now_delinq: Number of accounts currently delinquent

pub_rec_bankruptcies: Number of public record bankruptcies

tax_liens: Number of tax liens

Additional Credit Information

Secondary Applicant Information

revol_bal_joint: Joint revolving balance

sec_app_earliest_cr_line: Secondary applicant's earliest credit line

sec_app_inq_last_6mths: Secondary applicant's inquiries in the last 6 months

sec_app_mort_acc: Secondary applicant's number of mortgage accounts

sec_app_open_acc: Secondary applicant's number of open accounts

sec_app_revol_util: Secondary applicant's revolving utilization rate

sec_app_open_act_il: Secondary applicant's open installment loans

sec_app_num_rev_accts: Secondary applicant's number of revolving accounts

sec_app_chargeoff_within_12_mths: Secondary applicant's number of charge-offs within 12 months

sec_app_collections_12_mths_ex_med: Secondary applicant's collections excluding medical in the last 12 months

sec_app_mths_since_last_major_derog: Secondary applicant's months since the last major derogatory

**Recent Open Accounts and Inquiries**

open_acc_6m: Number of open accounts in the last 6 months

open_act_il: Number of open installment loans

open_il_12m: Number of installment loans opened in the last 12 months

open_il_24m: Number of installment loans opened in the last 24 months

mths_since_rcnt_il: Months since most recent installment loan opened
il_util: Installment loan utilization rate

open_rv_12m: Number of revolving accounts opened in the last 12 months

open_rv_24m: Number of revolving accounts opened in the last 24 months

max_bal_bc: Maximum balance on bank card

inq_fi: Number of personal finance inquiries

total_cu_tl: Number of credit union trades

inq_last_12m: Number of credit inquiries in the last 12 months

acc_open_past_24mths: Number of accounts opened in the past 24 months

mo_sin_old_il_acct: Months since oldest installment account opened

mo_sin_old_rev_tl_op: Months since oldest revolving account opened

mo_sin_rcnt_rev_tl_op: Months since most recent revolving account opened

mo_sin_rcnt_tl: Months since most recent account opened

mort_acc: Number of mortgage accounts

mths_since_recent_bc: Months since most recent bankcard account opened

mths_since_recent_bc_dlq: Months since recent bankcard delinquency

mths_since_recent_inq: Months since recent inquiry

mths_since_recent_revol_delinq: Months since recent revolving delinquency

--------------------------------------------------------------------------------------------

In [126]:
import numpy as np
import pandas as pd
from collections import Counter

In [143]:
# Load the data
file_path = '/content/CreditRiskDataset.csv'
df_original = pd.read_csv(file_path)

<ipython-input-143-52b23280f012>:3: DtypeWarning: Columns (0,1,2,3,4,7,13,18,19,24,25,27,28,29,30,31,32,34,36,37,38,39,40,41,42,43,44,46,49,50,51,53,54,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,113,114,115,116,117,118,119,120,121,123,124,125,126,127,128,129,130,131,132,133,134,135,136,138,139,140,141,142,143) have mixed types. Specify dtype option on import or set low_memory=False.
  df_original = pd.read_csv(file_path)

In [144]:
df_original.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
id  member_id loan_amnt funded_amnt funded_amnt_inv term       int_rate installment grade sub_grade emp_title                                emp_length home_ownership annual_inc verification_status issue_d  loan_status pymnt_plan url desc purpose            title                   zip_code addr_state dti   delinq_2yrs earliest_cr_line inq_last_6mths mths_since_last_delinq mths_since_last_record open_acc pub_rec revol_bal revol_util total_acc initial_list_status out_prncp out_prncp_inv total_pymnt total_pymnt_inv total_rec_prncp total_rec_int total_rec_late_fee recoveries collection_recovery_fee last_pymnt_d last_pymnt_amnt next_pymnt_d last_credit_pull_d collections_12_mths_ex_med mths_since_last_major_derog policy_code application_type annual_inc_joint dti_joint verification_status_joint acc_now_delinq tot_coll_amt tot_cur_bal open_acc_6m open_act_il open_il_12m open_il_24m mths_since_rcnt_il total_bal_il il_util open_rv_12m open_rv_24m max_bal_bc all_util total_rev_hi_lim inq_fi total_cu_tl inq_last_12m acc_open_past_24mths avg_cur_bal bc_open_to_buy bc_util chargeoff_within_12_mths delinq_amnt mo_sin_old_il_acct mo_sin_old_rev_tl_op mo_sin_rcnt_rev_tl_op mo_sin_rcnt_tl mort_acc mths_since_recent_bc mths_since_recent_bc_dlq mths_since_recent_inq mths_since_recent_revol_delinq num_accts_ever_120_pd num_actv_bc_tl num_actv_rev_tl num_bc_sats num_bc_tl num_il_tl num_op_rev_tl num_rev_accts num_rev_tl_bal_gt_0 num_sats num_tl_120dpd_2m num_tl_30dpd num_tl_90g_dpd_24m num_tl_op_past_12m pct_tl_nvr_dlq percent_bc_gt_75 pub_rec_bankruptcies tax_liens tot_hi_cred_lim total_bal_ex_mort total_bc_limit total_il_high_credit_limit revol_bal_joint sec_app_earliest_cr_line sec_app_inq_last_6mths sec_app_mort_acc sec_app_open_acc sec_app_revol_util sec_app_open_act_il sec_app_num_rev_accts sec_app_chargeoff_within_12_mths sec_app_collections_12_mths_ex_med sec_app_mths_since_last_major_derog hardship_flag hardship_type hardship_reason hardship_status deferral_term hardship_amount hardship_start_date hardship_end_date payment_plan_start_date hardship_length hardship_dpd hardship_loan_status orig_projected_additional_accrued_interest hardship_payoff_balance_amount hardship_last_payment_amount debt_settlement_flag debt_settlement_flag_date settlement_status settlement_date settlement_amount settlement_percentage                                    settlement_term
NaN NaN       20000     20000       20000            60 months  17.19%  499.1       C     C5        Front desk supervisor                    6 years    RENT           47000      Source Verified     Mar-2019 Issued      n          NaN NaN  debt_consolidation Debt consolidation      958xx    CA         14.02 0           Sep-2006         1              50                     NaN                    15       0       10687     19.7%      53        w                   20000.00  20000.00      0.0         0.00            0.00            0.00          0.0                0.0        0.0                     NaN          0.0             Apr-2019     Apr-2019           0                          50                          1           Individual       NaN              NaN       NaN                       0              0            31546       3           2           1           2           10                 20859        97      4           9           5909       42       54300            6      1           3            11                   2103        23647          30      0                        0           150                100                  1                     1              0        5                    NaN                      3                     50                             3                     3              4               8           19        19        13            33            4                   15       0                0            0                  5                  98             12.5             0                    0         75824           31546             33800          21524                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              21225     21225       21225            60 months  14.74%  502.05      C     C2        ceo                                      10+ years  MORTGAGE       225000     Not Verified        Mar-2019 Issued      n          NaN NaN  credit_card        Credit card refinancing 956xx    CA         16.8  0           Sep-1994         2              NaN                    110                    14       1       95868     87.7%      22        w                   21225.00  21225.00      0.0         0.00            0.00            0.00          0.0                0.0        0.0                     NaN          0.0             Apr-2019     Apr-2019           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            694793      1           5           2           4           3                  113558       76      0           1           17353      84       109300           1      0           4            5                    49628       12635          76.4    0                        0           126                294                  24                    3              4        30                   NaN                      1                     NaN                            0                     4              6               4           4         11        7             7             6                   14       0                0            0                  2                  100            50               1                    0         747075          209426            53500          128175                     NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              5000      5000        5000             36 months  17.97%  180.69      D     D1        NaN                                      NaN        MORTGAGE       62000      Not Verified        Mar-2019 Issued      n          NaN NaN  home_improvement   Home improvement        320xx    FL         19.82 1           Nov-1987         0              4                      NaN                    8        0       7285      77.5%      18        w                   5000.00   5000.00       0.0         0.00            0.00            0.00          0.0                0.0        0.0                     NaN          0.0             Apr-2019     Apr-2019           0                          4                           1           Individual       NaN              NaN       NaN                       0              0            206639      0           1           0           0           33                 24330        NaN     1           3           2318       78       9400             0      0           0            3                    25830       2115           77.5    0                        0           187                376                  9                     9              2        9                    NaN                      NaN                   4                              3                     6              6               6           6         7         6             9             6                   8        0                0            1                  1                  66.7           50               0                    0         255738          31615             9400           39938                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              20000     20000       20000            36 months   8.19%  628.49      A     A4        Executive Director of Guardian Advantage 1 year     MORTGAGE       200000     Not Verified        Mar-2019 Issued      n          NaN NaN  credit_card        Credit card refinancing 190xx    PA         22.66 1           Oct-2001         0              18                     NaN                    20       0       20984     32.1%      49        w                   20000.00  20000.00      0.0         0.00            0.00            0.00          0.0                0.0        0.0                     NaN          0.0             Apr-2019     Apr-2019           0                          48                          1           Individual       NaN              NaN       NaN                       0              0            326678      2           5           1           3           4                  63760        61      2           3           5097       50       64400            1      5           0            6                    17194       30437          38.4    0                        0           162                209                  2                     2              1        2                    18                       21                    18                             1                     7              9               9           15        20        14            27            9                   20       0                0            0                  3                  95.7           22.2             0                    0         448069          84744             49400          105180                     NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN

# **Since the first row contains note ; Skip the first row:**

In [145]:
df_original = pd.read_csv(file_path,skiprows=1)

<ipython-input-145-3830df8e3ecf>:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_original = pd.read_csv(file_path,skiprows=1)

In [129]:
df_original.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,20000.0,20000.0,20000.0,60 months,17.19%,499.10,C,C5,Front desk supervisor,6 years,RENT,47000.0,Source Verified,Mar-2019,Issued,n,NaN,NaN,debt_consolidation,Debt consolidation,958xx,CA,14.02,0.0,Sep-2006,1.0,50.0,NaN,15.0,0.0,10687.0,19.7%,53.0,w,20000.0,20000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Apr-2019,Apr-2019,0.0,50.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,31546.0,3.0,2.0,1.0,2.0,10.0,20859.0,97.0,4.0,9.0,5909.0,42.0,54300.0,6.0,1.0,3.0,11.0,2103.0,23647.0,30.0,0.0,0.0,150.0,100.0,1.0,1.0,0.0,5.0,NaN,3.0,50.0,3.0,3.0,4.0,8.0,19.0,19.0,13.0,33.0,4.0,15.0,0.0,0.0,0.0,5.0,98.0,12.5,0.0,0.0,75824.0,31546.0,33800.0,21524.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,21225.0,21225.0,21225.0,60 months,14.74%,502.05,C,C2,ceo,10+ years,MORTGAGE,225000.0,Not Verified,Mar-2019,Issued,n,NaN,NaN,credit_card,Credit card refinancing,956xx,CA,16.80,0.0,Sep-1994,2.0,NaN,110.0,14.0,1.0,95868.0,87.7%,22.0,w,21225.0,21225.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Apr-2019,Apr-2019,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,694793.0,1.0,5.0,2.0,4.0,3.0,113558.0,76.0,0.0,1.0,17353.0,84.0,109300.0,1.0,0.0,4.0,5.0,49628.0,12635.0,76.4,0.0,0.0,126.0,294.0,24.0,3.0,4.0,30.0,NaN,1.0,NaN,0.0,4.0,6.0,4.0,4.0,11.0,7.0,7.0,6.0,14.0,0.0,0.0,0.0,2.0,100.0,50.0,1.0,0.0,747075.0,209426.0,53500.0,128175.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000.0,5000.0,5000.0,36 months,17.97%,180.69,D,D1,NaN,NaN,MORTGAGE,62000.0,Not Verified,Mar-2019,Issued,n,NaN,NaN,home_improvement,Home improvement,320xx,FL,19.82,1.0,Nov-1987,0.0,4.0,NaN,8.0,0.0,7285.0,77.5%,18.0,w,5000.0,5000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Apr-2019,Apr-2019,0.0,4.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,206639.0,0.0,1.0,0.0,0.0,33.0,24330.0,NaN,1.0,3.0,2318.0,78.0,9400.0,0.0,0.0,0.0,3.0,25830.0,2115.0,77.5,0.0,0.0,187.0,376.0,9.0,9.0,2.0,9.0,NaN,NaN,4.0,3.0,6.0,6.0,6.0,6.0,7.0,6.0,9.0,6.0,8.0,0.0,0.0,1.0,1.0,66.7,50.0,0.0,0.0,255738.0,31615.0,9400.0,39938.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,20000.0,20000.0,20000.0,36 months,8.19%,628.49,A,A4,Executive Director of Guardian Advantage,1 year,MORTGAGE,200000.0,Not Verified,Mar-2019,Issued,n,NaN,NaN,credit_card,Credit card refinancing,190xx,PA,22.66,1.0,Oct-2001,0.0,18.0,NaN,20.0,0.0,20984.0,32.1%,49.0,w,20000.0,20000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Apr-2019,Apr-2019,0.0,48.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,326678.0,2.0,5.0,1.0,3.0,4.0,63760.0,61.0,2.0,3.0,5097.0,50.0,64400.0,1.0,5.0,0.0,6.0,17194.0,30437.0,38.4,0.0,0.0,162.0,209.0,2.0,2.0,1.0,2.0,18.0,21.0,18.0,1.0,7.0,9.0,9.0,15.0,20.0,14.0,27.0,9.0,20.0,0.0,0.0,0.0,3.0,95.7,22.2,0.0,0.0,448069.0,84744.0,49400.0,105180.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,12000.0,12000.0,12000.0,60 months,15.57%,289.09,C,C3,Computer Operator,5 years,MORTGAGE,49000.0,Source Verified,Mar-2019,Issued,n,NaN,NaN,debt_consolidation,Debt consolidation,152xx,PA,13.47,0.0,Apr-1993,0.0,38.0,NaN,18.0,0.0,17672.0,48.2%,36.0,w,12000.0,12000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Apr-2019,Apr-2019,0.0,38.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,143079.0,2.0,4.0,0.0,0.0,51.0,88353.0,128.0,4.0,6.0,3587.0,100.0,36700.0,0.0,8.0,1.0,6.0,7949.0,14848.0,39.1,1.0,0.0,144.0,311.0,3.0,3.0,5.0,3.0,38.0,11.0,38.0,4.0,5.0,10.0,7.0,11.0,12.0,12.0,19.0,10.0,18.0,0.0,0.0,0.0,4.0,86.1,14.3,0.0,0.0,189260.0,106025.0,24400.0,68860.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
df_original.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
115672,NaN,NaN,16000.0,16000.0,16000.0,36 months,16.14%,563.62,C,C4,Estimator/Supervisor,10+ years,MORTGAGE,32000.0,Source Verified,Jan-2019,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,925xx,CA,20.89,0.0,Dec-2010,0.0,35.0,117.0,13.0,1.0,17066.0,49.9%,15.0,f,14940.62,14940.62,1676.51,1676.51,1059.38,617.13,0.0,0.0,0.0,Apr-2019,563.62,May-2019,Apr-2019,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,17066.0,1.0,0.0,0.0,0.0,55.0,0.0,NaN,3.0,3.0,2353.0,50.0,34200.0,0.0,0.0,1.0,3.0,1313.0,6446.0,60.7,0.0,0.0,55.0,96.0,1.0,1.0,0.0,1.0,35.0,12.0,35.0,0.0,7.0,8.0,8.0,8.0,1.0,13.0,14.0,8.0,13.0,0.0,0.0,0.0,3.0,93.3,37.5,1.0,0.0,34200.0,17066.0,16400.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
115673,NaN,NaN,16000.0,16000.0,16000.0,60 months,11.31%,350.36,B,B3,MATERIAL HANDLER,5 years,MORTGAGE,72000.0,Verified,Jan-2019,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,850xx,AZ,7.02,2.0,Sep-2005,0.0,8.0,64.0,12.0,1.0,11882.0,37.1%,39.0,w,15395.66,15395.66,1041.03,1041.03,604.34,436.69,0.0,0.0,0.0,Apr-2019,350.36,May-2019,Apr-2019,0.0,8.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,225413.0,0.0,2.0,0.0,0.0,28.0,62953.0,79.0,0.0,0.0,5568.0,45.0,32000.0,2.0,2.0,4.0,1.0,18784.0,11705.0,49.1,2.0,0.0,159.0,129.0,25.0,24.0,3.0,25.0,NaN,1.0,9.0,2.0,4.0,5.0,5.0,9.0,20.0,9.0,16.0,5.0,12.0,0.0,0.0,2.0,0.0,94.3,0.0,1.0,0.0,251486.0,74835.0,23000.0,63090.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
115674,NaN,NaN,29250.0,29250.0,29250.0,60 months,18.94%,757.80,D,D2,sr register csa,7 years,MORTGAGE,65000.0,Verified,Jan-2019,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,774xx,TX,29.52,0.0,Jan-2011,0.0,NaN,NaN,20.0,0.0,38465.0,69%,22.0,w,28347.49,28347.49,2211.84,2211.84,902.51,1309.33,0.0,0.0,0.0,Apr-2019,757.80,May-2019,Apr-2019,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204764.0,0.0,1.0,0.0,1.0,17.0,20323.0,79.0,1.0,3.0,13874.0,69.0,55505.0,0.0,0.0,0.0,4.0,10238.0,2985.0,87.0,0.0,0.0,78.0,95.0,7.0,7.0,1.0,19.0,NaN,13.0,NaN,0.0,13.0,18.0,13.0,13.0,3.0,18.0,18.0,18.0,20.0,NaN,0.0,0.0,1.0,100.0,76.9,0.0,0.0,237833.0,58788.0,38800.0,25728.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
115675,Total amount funded in policy code 1: 1928448350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115676,Total amount funded in policy code 2: 799382986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [146]:
df_original.shape

(115677, 144)



# **Since last two rows have all NAN values, slice them off:**

In [147]:
df = df_original.iloc[:-2,:]

In [148]:
df.shape

(115675, 144)

# **Displaying all columns without ....:**

In [149]:
pd.set_option('display.max_columns', None)  # None means unlimited columns
# pd.set_option('display.max_rows', None)     # None means unlimited rows
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,20000.0,20000.0,20000.0,60 months,17.19%,499.10,C,C5,Front desk supervisor,6 years,RENT,47000.0,Source Verified,Mar-2019,Issued,n,NaN,NaN,debt_consolidation,Debt consolidation,958xx,CA,14.02,0.0,Sep-2006,1.0,50.0,NaN,15.0,0.0,10687.0,19.7%,53.0,w,20000.0,20000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Apr-2019,Apr-2019,0.0,50.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,31546.0,3.0,2.0,1.0,2.0,10.0,20859.0,97.0,4.0,9.0,5909.0,42.0,54300.0,6.0,1.0,3.0,11.0,2103.0,23647.0,30.0,0.0,0.0,150.0,100.0,1.0,1.0,0.0,5.0,NaN,3.0,50.0,3.0,3.0,4.0,8.0,19.0,19.0,13.0,33.0,4.0,15.0,0.0,0.0,0.0,5.0,98.0,12.5,0.0,0.0,75824.0,31546.0,33800.0,21524.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,21225.0,21225.0,21225.0,60 months,14.74%,502.05,C,C2,ceo,10+ years,MORTGAGE,225000.0,Not Verified,Mar-2019,Issued,n,NaN,NaN,credit_card,Credit card refinancing,956xx,CA,16.80,0.0,Sep-1994,2.0,NaN,110.0,14.0,1.0,95868.0,87.7%,22.0,w,21225.0,21225.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Apr-2019,Apr-2019,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,694793.0,1.0,5.0,2.0,4.0,3.0,113558.0,76.0,0.0,1.0,17353.0,84.0,109300.0,1.0,0.0,4.0,5.0,49628.0,12635.0,76.4,0.0,0.0,126.0,294.0,24.0,3.0,4.0,30.0,NaN,1.0,NaN,0.0,4.0,6.0,4.0,4.0,11.0,7.0,7.0,6.0,14.0,0.0,0.0,0.0,2.0,100.0,50.0,1.0,0.0,747075.0,209426.0,53500.0,128175.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000.0,5000.0,5000.0,36 months,17.97%,180.69,D,D1,NaN,NaN,MORTGAGE,62000.0,Not Verified,Mar-2019,Issued,n,NaN,NaN,home_improvement,Home improvement,320xx,FL,19.82,1.0,Nov-1987,0.0,4.0,NaN,8.0,0.0,7285.0,77.5%,18.0,w,5000.0,5000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Apr-2019,Apr-2019,0.0,4.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,206639.0,0.0,1.0,0.0,0.0,33.0,24330.0,NaN,1.0,3.0,2318.0,78.0,9400.0,0.0,0.0,0.0,3.0,25830.0,2115.0,77.5,0.0,0.0,187.0,376.0,9.0,9.0,2.0,9.0,NaN,NaN,4.0,3.0,6.0,6.0,6.0,6.0,7.0,6.0,9.0,6.0,8.0,0.0,0.0,1.0,1.0,66.7,50.0,0.0,0.0,255738.0,31615.0,9400.0,39938.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,20000.0,20000.0,20000.0,36 months,8.19%,628.49,A,A4,Executive Director of Guardian Advantage,1 year,MORTGAGE,200000.0,Not Verified,Mar-2019,Issued,n,NaN,NaN,credit_card,Credit card refinancing,190xx,PA,22.66,1.0,Oct-2001,0.0,18.0,NaN,20.0,0.0,20984.0,32.1%,49.0,w,20000.0,20000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Apr-2019,Apr-2019,0.0,48.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,326678.0,2.0,5.0,1.0,3.0,4.0,63760.0,61.0,2.0,3.0,5097.0,50.0,64400.0,1.0,5.0,0.0,6.0,17194.0,30437.0,38.4,0.0,0.0,162.0,209.0,2.0,2.0,1.0,2.0,18.0,21.0,18.0,1.0,7.0,9.0,9.0,15.0,20.0,14.0,27.0,9.0,20.0,0.0,0.0,0.0,3.0,95.7,22.2,0.0,0.0,448069.0,84744.0,49400.0,105180.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,12000.0,12000.0,12000.0,60 months,15.57%,289.09,C,C3,Computer Operator,5 years,MORTGAGE,49000.0,Source Verified,Mar-2019,Issued,n,NaN,NaN,debt_consolidation,Debt consolidation,152xx,PA,13.47,0.0,Apr-1993,0.0,38.0,NaN,18.0,0.0,17672.0,48.2%,36.0,w,12000.0,12000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Apr-2019,Apr-2019,0.0,38.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,143079.0,2.0,4.0,0.0,0.0,51.0,88353.0,128.0,4.0,6.0,3587.0,100.0,36700.0,0.0,8.0,1.0,6.0,7949.0,14848.0,39.1,1.0,0.0,144.0,311.0,3.0,3.0,5.0,3.0,38.0,11.0,38.0,4.0,5.0,10.0,7.0,11.0,12.0,12.0,19.0,10.0,18.0,0.0,0.0,0.0,4.0,86.1,14.3,0.0,0.0,189260.0,106025.0,24400.0,68860.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [150]:
# Drop the null columns where all values are null
df = df.dropna(axis=1, how='all') # how = any --> removes col if any value in the col is null and all removes col if all values in the col are null

In [151]:
df.shape

(115675, 120)

# **Drop the cols with large number of  nan values:**

In [152]:
# Calculate the percentage of missing values for each column
missing_percent_colwise = df.isna().mean() * 100 # mean=sum/N
missing_percent_colwise

loan_amnt                               0.000000
funded_amnt                             0.000000
funded_amnt_inv                         0.000000
term                                    0.000000
int_rate                                0.000000
installment                             0.000000
grade                                   0.000000
sub_grade                               0.000000
emp_title                              16.873136
emp_length                              9.596715
home_ownership                          0.000000
annual_inc                              0.000000
verification_status                     0.000000
issue_d                                 0.000000
loan_status                             0.000000
pymnt_plan                              0.000000
purpose                                 0.000000
title                                   0.000000
zip_code                                0.000000
addr_state                              0.000000
dti                                     0.222174
delinq_2yrs                             0.000000
earliest_cr_line                        0.000000
inq_last_6mths                          0.000000
mths_since_last_delinq                 56.882645
mths_since_last_record                 88.395937
open_acc                                0.000000
pub_rec                                 0.000000
revol_bal                               0.000000
revol_util                              0.111519
total_acc                               0.000000
initial_list_status                     0.000000
out_prncp                               0.000000
out_prncp_inv                           0.000000
total_pymnt                             0.000000
total_pymnt_inv                         0.000000
total_rec_prncp                         0.000000
total_rec_int                           0.000000
total_rec_late_fee                      0.000000
recoveries                              0.000000
collection_recovery_fee                 0.000000
last_pymnt_d                           16.261941
last_pymnt_amnt                         0.000000
next_pymnt_d                            1.900151
last_credit_pull_d                      0.001729
collections_12_mths_ex_med              0.000000
mths_since_last_major_derog            78.389453
policy_code                             0.000000
application_type                        0.000000
annual_inc_joint                       85.579425
dti_joint                              85.579425
verification_status_joint              87.357683
acc_now_delinq                          0.000000
tot_coll_amt                            0.000000
tot_cur_bal                             0.000000
open_acc_6m                             0.000000
open_act_il                             0.000000
open_il_12m                             0.000000
open_il_24m                             0.000000
mths_since_rcnt_il                      3.040415
total_bal_il                            0.000000
il_util                                14.972120
open_rv_12m                             0.000000
open_rv_24m                             0.000000
max_bal_bc                              0.000000
all_util                                0.020748
total_rev_hi_lim                        0.000000
inq_fi                                  0.000000
total_cu_tl                             0.000000
inq_last_12m                            0.000000
acc_open_past_24mths                    0.000000
avg_cur_bal                             0.006051
bc_open_to_buy                          1.143722
bc_util                                 1.191269
chargeoff_within_12_mths                0.000000
delinq_amnt                             0.000000
mo_sin_old_il_acct                      3.040415
mo_sin_old_rev_tl_op                    0.000000
mo_sin_rcnt_rev_tl_op                   0.000000
mo_sin_rcnt_tl                          0.000000
mort_acc                                0.000000
mths_since_recent_bc                    1.087530
mths_since_recent_bc_dlq               80.464232
mths_since_recent_inq                  12.411498
mths_since_recent_revol_delinq         71.561703
num_accts_ever_120_pd                   0.000000
num_actv_bc_tl                          0.000000
num_actv_rev_tl                         0.000000
num_bc_sats                             0.000000
num_bc_tl                               0.000000
num_il_tl                               0.000000
num_op_rev_tl                           0.000000
num_rev_accts                           0.000000
num_rev_tl_bal_gt_0                     0.000000
num_sats                                0.000000
num_tl_120dpd_2m                        2.719689
num_tl_30dpd                            0.000000
num_tl_90g_dpd_24m                      0.000000
num_tl_op_past_12m                      0.000000
pct_tl_nvr_dlq                          0.000000
percent_bc_gt_75                        1.148909
pub_rec_bankruptcies                    0.000000
tax_liens                               0.000000
tot_hi_cred_lim                         0.000000
total_bal_ex_mort                       0.000000
total_bc_limit                          0.000000
total_il_high_credit_limit              0.000000
revol_bal_joint                        85.579425
sec_app_earliest_cr_line               85.579425
sec_app_inq_last_6mths                 85.579425
sec_app_mort_acc                       85.579425
sec_app_open_acc                       85.579425
sec_app_revol_util                     85.778258
sec_app_open_act_il                    85.579425
sec_app_num_rev_accts                  85.579425
sec_app_chargeoff_within_12_mths       85.579425
sec_app_collections_12_mths_ex_med     85.579425
sec_app_mths_since_last_major_derog    95.763129
hardship_flag                           0.000000
debt_settlement_flag                    0.000000
dtype: float64

In [153]:
# Categorize columns based on the percentage of missing values
low_missing_cols = missing_percent_colwise[missing_percent_colwise <= 20].index.tolist()
moderate_missing_cols = missing_percent_colwise[(missing_percent_colwise > 20) & (missing_percent_colwise <= 60)].index.tolist()
high_missing_cols = missing_percent_colwise[missing_percent_colwise > 60].index.tolist()

print(f"Low missing value columns (0-20%): {len(low_missing_cols)} columns")
print(f"Moderate missing value columns (20-60%): {len(moderate_missing_cols)} columns")
print(f"High missing value columns (60-100%): {len(high_missing_cols)} columns")

Low missing value columns (0-20%): 101 columns
Moderate missing value columns (20-60%): 1 columns
High missing value columns (60-100%): 18 columns

In [154]:
high_missing_cols

['mths_since_last_record',
 'mths_since_last_major_derog',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_revol_delinq',
 'revol_bal_joint',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog']

In [155]:
# Drop high missing value columns
df.drop(columns=high_missing_cols, axis=1, inplace=True)

In [156]:
df.shape

(115675, 102)

In [157]:
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    print(f"{col}: {df[col].unique()}")

term: [' 60 months' ' 36 months']
int_rate: [' 17.19%' ' 14.74%' ' 17.97%' '  8.19%' ' 15.57%' '  7.56%' '  7.02%'
 ' 12.40%' '  8.81%' ' 13.90%' ' 16.40%' ' 28.80%' ' 20.00%' ' 25.00%'
 '  6.46%' ' 13.08%' ' 11.02%' ' 11.71%' ' 22.50%' ' 10.33%' ' 29.00%'
 ' 30.84%' ' 11.31%' ' 28.90%' ' 28.92%' ' 30.79%' ' 16.91%' ' 18.94%'
 ' 28.95%' ' 13.56%' ' 12.98%' ' 10.72%' ' 15.02%' ' 20.89%' ' 14.47%'
 ' 19.92%' ' 22.35%' ' 11.80%' ' 16.14%' ' 28.97%' ' 30.75%' ' 24.37%'
 ' 25.34%' ' 23.40%' ' 29.35%' ' 26.31%' ' 27.27%' ' 30.65%' ' 29.69%'
 ' 30.17%' '  6.00%' ' 30.89%' ' 28.72%']
grade: ['C' 'D' 'A' 'B' 'E' 'G' 'F']
sub_grade: ['C5' 'C2' 'D1' 'A4' 'C3' 'A3' 'A2' 'B4' 'A5' 'C1' 'C4' 'D5' 'D2' 'D4'
 'A1' 'B5' 'B2' 'B3' 'D3' 'B1' 'E5' 'G2' 'E1' 'E2' 'G1' 'E3' 'E4' 'F5'
 'F1' 'F4' 'F2' 'F3' 'G3']
emp_title: ['Front desk supervisor' 'ceo' nan ... 'President - North America'
 'Estimator/Supervisor' 'sr register csa']
emp_length: ['6 years' '10+ years' nan '1 year' '5 years' '8 years' '< 1 year'
 '4 years' '2 years' '3 years' '7 years' '9 years']
home_ownership: ['RENT' 'MORTGAGE' 'OWN' 'ANY' 'NONE']
verification_status: ['Source Verified' 'Not Verified' 'Verified']
issue_d: ['Mar-2019' 'Feb-2019' 'Jan-2019']
loan_status: ['Issued' 'Fully Paid' 'Current' 'Charged Off' 'In Grace Period'
 'Late (16-30 days)' 'Late (31-120 days)']
pymnt_plan: ['n']
purpose: ['debt_consolidation' 'credit_card' 'home_improvement' 'medical' 'other'
 'car' 'major_purchase' 'small_business' 'house' 'moving' 'vacation'
 'renewable_energy']
title: ['Debt consolidation' 'Credit card refinancing' 'Home improvement'
 'Medical expenses' 'Other' 'Car financing' 'Major purchase' 'Business'
 'Home buying' 'Moving and relocation' 'Vacation' 'Green loan']
zip_code: ['958xx' '956xx' '320xx' '190xx' '152xx' '857xx' '600xx' '306xx' '489xx'
 '765xx' '113xx' '853xx' '327xx' '436xx' '481xx' '494xx' '296xx' '183xx'
 '211xx' '907xx' '637xx' '309xx' '610xx' '305xx' '704xx' '331xx' '922xx'
 '300xx' '982xx' '117xx' '333xx' '724xx' '531xx' '560xx' '463xx' '749xx'
 '851xx' '103xx' '480xx' '112xx' '233xx' '462xx' '153xx' '930xx' '329xx'
 '140xx' '461xx' '787xx' '280xx' '487xx' '060xx' '297xx' '980xx' '902xx'
 '371xx' '144xx' '919xx' '828xx' '337xx' '114xx' '338xx' '561xx' '953xx'
 '973xx' '852xx' '104xx' '271xx' '904xx' '430xx' '633xx' '341xx' '240xx'
 '957xx' '109xx' '640xx' '273xx' '471xx' '025xx' '402xx' '100xx' '281xx'
 '921xx' '077xx' '879xx' '581xx' '730xx' '360xx' '739xx' '075xx' '201xx'
 '606xx' '954xx' '080xx' '701xx' '330xx' '951xx' '334xx' '275xx' '478xx'
 '774xx' '212xx' '554xx' '207xx' '242xx' '452xx' '313xx' '530xx' '950xx'
 '229xx' '450xx' '791xx' '377xx' '082xx' '934xx' '115xx' '105xx' '441xx'
 '843xx' '836xx' '482xx' '370xx' '550xx' '427xx' '661xx' '827xx' '120xx'
 '294xx' '350xx' '068xx' '802xx' '495xx' '596xx' '648xx' '024xx' '761xx'
 '284xx' '410xx' '706xx' '752xx' '961xx' '038xx' '820xx' '282xx' '286xx'
 '924xx' '743xx' '127xx' '645xx' '937xx' '773xx' '891xx' '770xx' '703xx'
 '021xx' '270xx' '945xx' '644xx' '116xx' '342xx' '034xx' '782xx' '272xx'
 '361xx' '062xx' '396xx' '786xx' '546xx' '335xx' '023xx' '890xx' '151xx'
 '063xx' '173xx' '972xx' '488xx' '967xx' '040xx' '917xx' '968xx' '085xx'
 '234xx' '496xx' '850xx' '794xx' '935xx' '900xx' '601xx' '990xx' '217xx'
 '906xx' '111xx' '468xx' '431xx' '070xx' '119xx' '676xx' '542xx' '076xx'
 '717xx' '208xx' '380xx' '290xx' '971xx' '433xx' '928xx' '997xx' '840xx'
 '925xx' '986xx' '952xx' '587xx' '130xx' '775xx' '083xx' '800xx' '365xx'
 '897xx' '812xx' '191xx' '616xx' '210xx' '027xx' '760xx' '605xx' '378xx'
 '641xx' '381xx' '421xx' '490xx' '390xx' '206xx' '200xx' '535xx' '926xx'
 '364xx' '061xx' '010xx' '232xx' '167xx' '856xx' '762xx' '302xx' '871xx'
 '548xx' '125xx' '878xx' '067xx' '927xx' '346xx' '672xx' '195xx' '863xx'
 '720xx' '492xx' '328xx' '454xx' '086xx' '611xx' '017xx' '719xx' '823xx'
 '253xx' '630xx' '809xx' '283xx' '315xx' '755xx' '763xx' '170xx' '347xx'
 '384xx' '557xx' '713xx' '449xx' '175xx' '367xx' '551xx' '238xx' '374xx'
 '585xx' '959xx' '197xx' '815xx' '166xx' '464xx' '545xx' '336xx' '030xx'
 '604xx' '783xx' '018xx' '913xx' '681xx' '215xx' '107xx' '189xx' '975xx'
 '386xx' '219xx' '939xx' '276xx' '314xx' '660xx' '970xx' '128xx' '323xx'
 '198xx' '362xx' '194xx' '801xx' '567xx' '936xx' '032xx' '224xx' '218xx'
 '235xx' '352xx' '301xx' '806xx' '458xx' '179xx' '020xx' '923xx' '045xx'
 '484xx' '221xx' '941xx' '373xx' '948xx' '920xx' '376xx' '145xx' '590xx'
 '011xx' '223xx' '026xx' '758xx' '620xx' '983xx' '156xx' '751xx' '292xx'
 '071xx' '456xx' '442xx' '571xx' '658xx' '894xx' '147xx' '565xx' '700xx'
 '467xx' '731xx' '810xx' '915xx' '949xx' '243xx' '142xx' '905xx' '443xx'
 '016xx' '393xx' '064xx' '707xx' '385xx' '553xx' '277xx' '033xx' '693xx'
 '028xx' '566xx' '837xx' '978xx' '721xx' '785xx' '122xx' '826xx' '814xx'
 '465xx' '910xx' '123xx' '598xx' '379xx' '805xx' '288xx' '324xx' '738xx'
 '453xx' '914xx' '141xx' '960xx' '650xx' '735xx' '883xx' '657xx' '895xx'
 '405xx' '440xx' '646xx' '577xx' '740xx' '358xx' '870xx' '295xx' '148xx'
 '634xx' '756xx' '912xx' '833xx' '303xx' '479xx' '180xx' '993xx' '222xx'
 '750xx' '357xx' '460xx' '438xx' '310xx' '287xx' '946xx' '015xx' '244xx'
 '683xx' '037xx' '992xx' '073xx' '231xx' '344xx' '671xx' '227xx' '573xx'
 '426xx' '779xx' '245xx' '160xx' '570xx' '594xx' '841xx' '864xx' '193xx'
 '844xx' '220xx' '325xx' '322xx' '274xx' '608xx' '081xx' '088xx' '998xx'
 '486xx' '776xx' '241xx' '349xx' '665xx' '722xx' '799xx' '838xx' '932xx'
 '446xx' '832xx' '607xx' '254xx' '855xx' '163xx' '940xx' '977xx' '053xx'
 '029xx' '499xx' '019xx' '541xx' '383xx' '688xx' '435xx' '532xx' '908xx'
 '547xx' '497xx' '580xx' '933xx' '209xx' '425xx' '265xx' '355xx' '626xx'
 '129xx' '400xx' '356xx' '985xx' '199xx' '087xx' '042xx' '339xx' '187xx'
 '491xx' '716xx' '050xx' '804xx' '101xx' '790xx' '781xx' '757xx' '255xx'
 '326xx' '476xx' '483xx' '822xx' '670xx' '943xx' '257xx' '307xx' '172xx'
 '177xx' '312xx' '754xx' '847xx' '424xx' '185xx' '176xx' '588xx' '110xx'
 '470xx' '537xx' '074xx' '134xx' '615xx' '727xx' '133xx' '291xx' '947xx'
 '793xx' '391xx' '225xx' '705xx' '723xx' '236xx' '597xx' '318xx' '066xx'
 '788xx' '150xx' '627xx' '631xx' '984xx' '321xx' '394xx' '599xx' '880xx'
 '769xx' '317xx' '689xx' '439xx' '931xx' '121xx' '766xx' '647xx' '544xx'
 '473xx' '226xx' '423xx' '726xx' '216xx' '448xx' '299xx' '230xx' '540xx'
 '052xx' '260xx' '685xx' '673xx' '974xx' '764xx' '078xx' '549xx' '444xx'
 '981xx' '618xx' '014xx' '106xx' '622xx' '181xx' '582xx' '279xx' '592xx'
 '065xx' '455xx' '262xx' '041xx' '591xx' '054xx' '165xx' '412xx' '474xx'
 '784xx' '186xx' '057xx' '629xx' '674xx' '447xx' '898xx' '780xx' '966xx'
 '575xx' '411xx' '563xx' '559xx' '351xx' '874xx' '285xx' '432xx' '395xx'
 '174xx' '136xx' '656xx' '767xx' '708xx' '072xx' '534xx' '434xx' '239xx'
 '725xx' '712xx' '049xx' '259xx' '445xx' '304xx' '624xx' '132xx' '666xx'
 '918xx' '613xx' '043xx' '079xx' '406xx' '686xx' '728xx' '539xx' '603xx'
 '451xx' '403xx' '126xx' '466xx' '118xx' '089xx' '881xx' '916xx' '159xx'
 '278xx' '759xx' '797xx' '662xx' '251xx' '903xx' '372xx' '944xx' '031xx'
 '714xx' '675xx' '741xx' '056xx' '263xx' '995xx' '829xx' '368xx' '472xx'
 '744xx' '729xx' '366xx' '457xx' '651xx' '803xx' '988xx' '261xx' '619xx'
 '158xx' '161xx' '237xx' '022xx' '013xx' '044xx' '746xx' '359xx' '687xx'
 '401xx' '012xx' '813xx' '258xx' '538xx' '131xx' '477xx' '404xx' '124xx'
 '157xx' '834xx' '139xx' '543xx' '808xx' '267xx' '955xx' '469xx' '795xx'
 '164xx' '989xx' '293xx' '614xx' '146xx' '976xx' '778xx' '748xx' '252xx'
 '228xx' '796xx' '652xx' '437xx' '493xx' '617xx' '628xx' '718xx' '562xx'
 '387xx' '388xx' '875xx' '667xx' '882xx' '678xx' '807xx' '184xx' '298xx'
 '583xx' '319xx' '680xx' '747xx' '609xx' '711xx' '564xx' '389xx' '135xx'
 '612xx' '846xx' '168xx' '249xx' '824xx' '035xx' '363xx' '154xx' '789xx'
 '289xx' '991xx' '047xx' '877xx' '911xx' '768xx' '214xx' '655xx' '734xx'
 '653xx' '058xx' '485xx' '574xx' '996xx' '584xx' '602xx' '247xx' '625xx'
 '171xx' '710xx' '669xx' '178xx' '108xx' '250xx' '048xx' '398xx' '552xx'
 '860xx' '069xx' '422xx' '397xx' '417xx' '143xx' '816xx' '188xx' '684xx'
 '392xx' '623xx' '102xx' '558xx' '137xx' '636xx' '811xx' '407xx' '798xx'
 '196xx' '638xx' '475xx' '691xx' '036xx' '736xx' '498xx' '354xx' '777xx'
 '308xx' '835xx' '316xx' '138xx' '149xx' '046xx' '825xx' '155xx' '692xx'
 '845xx' '999xx' '690xx' '668xx' '182xx' '051xx' '420xx' '586xx' '859xx'
 '737xx' '169xx' '415xx' '382xx' '039xx' '865xx' '556xx' '084xx' '654xx'
 '635xx' '162xx' '677xx' '595xx' '873xx' '745xx' '792xx' '593xx' '413xx'
 '858xx' '264xx' '418xx' '246xx' '679xx' '091xx' '831xx' '248xx' '963xx'
 '266xx' '979xx' '893xx' '256xx' '572xx' '639xx' '664xx' '202xx' '753xx'
 '569xx' '416xx' '772xx' '409xx' '369xx' '094xx' '414xx' '830xx' '059xx'
 '332xx' '096xx' '965xx' '861xx' '962xx' '268xx' '311xx' '090xx' '994xx'
 '204xx' '408xx' '576xx' '896xx']
addr_state: ['CA' 'FL' 'PA' 'AZ' 'IL' 'GA' 'MI' 'TX' 'NY' 'OH' 'SC' 'MD' 'MO' 'LA'
 'WA' 'AR' 'WI' 'MN' 'IN' 'OK' 'VA' 'NC' 'CT' 'TN' 'WY' 'OR' 'MA' 'KY'
 'NJ' 'NM' 'ND' 'AL' 'UT' 'ID' 'KS' 'CO' 'MT' 'NH' 'NV' 'MS' 'HI' 'ME'
 'AK' 'DC' 'WV' 'DE' 'NE' 'SD' 'RI' 'VT']
earliest_cr_line: ['Sep-2006' 'Sep-1994' 'Nov-1987' 'Oct-2001' 'Apr-1993' 'Oct-2003'
 'Oct-1995' 'Feb-1997' 'Sep-2001' 'Mar-2006' 'Feb-1996' 'Jan-2002'
 'Jun-2004' 'Aug-2005' 'Nov-1992' 'Aug-2006' 'May-2010' 'Jul-2002'
 'May-2007' 'Nov-2005' 'Dec-2003' 'Jul-1995' 'Jul-2007' 'Jan-2007'
 'Apr-1996' 'Mar-1993' 'Feb-2003' 'Jul-1996' 'Jul-2005' 'Jan-2012'
 'Feb-1993' 'Dec-2009' 'Dec-1987' 'Oct-2005' 'Feb-2008' 'May-1999'
 'Mar-2011' 'Apr-2005' 'Aug-2000' 'Sep-2009' 'May-1995' 'Mar-2008'
 'Aug-2001' 'Mar-2007' 'Apr-2001' 'Aug-2004' 'Nov-2012' 'Mar-2012'
 'Sep-2010' 'Jun-2007' 'Dec-1990' 'Jul-2006' 'Mar-1997' 'Dec-1983'
 'Aug-2010' 'May-1989' 'Oct-1975' 'Sep-2005' 'Jul-2003' 'Feb-2009'
 'Sep-2007' 'Oct-2014' 'Jan-2008' 'May-1993' 'Jul-2011' 'Nov-1999'
 'Aug-2002' 'Jan-2010' 'Mar-2005' 'Apr-2006' 'Nov-2011' 'Jun-1998'
 'Dec-2004' 'Nov-2004' 'Mar-2010' 'Feb-1995' 'Jan-2000' 'Apr-2009'
 'Sep-2003' 'Nov-1975' 'Mar-1996' 'Dec-1991' 'Apr-2007' 'Mar-2004'
 'Nov-1995' 'Feb-2013' 'Oct-1996' 'Jun-1984' 'Mar-1992' 'Sep-1980'
 'Feb-1999' 'Aug-2007' 'Jul-2001' 'Dec-1998' 'Dec-1999' 'Jul-1988'
 'Feb-2007' 'Jul-2009' 'Mar-1991' 'Feb-2001' 'Jul-1993' 'Dec-2005'
 'Nov-2010' 'Jun-2006' 'May-2014' 'May-1996' 'Dec-2001' 'Dec-2002'
 'May-2009' 'Apr-1990' 'May-2002' 'Oct-1999' 'Jun-1999' 'Aug-1994'
 'Nov-2003' 'May-2008' 'Jan-2004' 'Dec-2013' 'Sep-1997' 'Oct-1992'
 'Nov-2009' 'Dec-1996' 'Apr-1998' 'Oct-2006' 'May-2001' 'Jan-2006'
 'Mar-1989' 'May-2006' 'May-1981' 'May-2005' 'Sep-2004' 'Apr-2008'
 'Aug-1996' 'Nov-2002' 'Dec-1993' 'Jul-1998' 'Aug-1998' 'Oct-1994'
 'Dec-2011' 'Feb-1987' 'Jul-2015' 'Mar-2015' 'Jan-2001' 'Jan-2005'
 'May-2015' 'May-2004' 'Jun-2008' 'Jul-2013' 'Nov-1996' 'Mar-1974'
 'Apr-2014' 'Oct-2008' 'Feb-2005' 'Apr-1992' 'Sep-1984' 'Feb-2011'
 'Dec-2008' 'Jun-2012' 'Sep-2013' 'Aug-2008' 'Jan-1993' 'Jun-1997'
 'Nov-2007' 'Dec-1992' 'Dec-2007' 'Jul-2010' 'Mar-2002' 'Aug-1993'
 'Nov-1997' 'Sep-2008' 'Aug-1999' 'Mar-2001' 'Jan-2003' 'May-2003'
 'Jun-2011' 'Sep-1977' 'Aug-2012' 'Nov-2006' 'Apr-2012' 'Apr-2004'
 'Jun-1992' 'Apr-2000' 'Jul-1974' 'Jan-2014' 'Jun-2014' 'May-2013'
 'May-1983' 'Oct-2010' 'Jan-1986' 'Mar-2009' 'Nov-1998' 'Dec-1994'
 'Jul-1999' 'May-2012' 'Apr-2003' 'Mar-2003' 'Jun-1995' 'Feb-2002'
 'Jan-1975' 'Apr-1999' 'Jul-1989' 'Jan-2013' 'May-2000' 'Nov-2000'
 'Feb-1991' 'Jul-1992' 'Jan-1997' 'Oct-1991' 'Feb-2010' 'Jul-2000'
 'Jul-2012' 'Aug-1997' 'Aug-2009' 'Dec-2012' 'Mar-1961' 'Sep-2012'
 'Jun-2002' 'Oct-1985' 'Aug-2014' 'Feb-2012' 'Jun-2001' 'Sep-1978'
 'Jun-1994' 'May-1990' 'May-1991' 'Jun-2003' 'Feb-2004' 'Oct-2002'
 'Sep-2011' 'Oct-1990' 'Dec-2006' 'Mar-1986' 'Oct-2000' 'Nov-1994'
 'Jun-2009' 'Sep-1998' 'Dec-2000' 'Jul-1997' 'Jul-2008' 'Jan-2015'
 'Mar-1988' 'Aug-2003' 'Jan-2011' 'Nov-1980' 'Jun-1983' 'Nov-1970'
 'Sep-2000' 'Aug-1995' 'Feb-1989' 'Jul-2004' 'Jun-2005' 'Aug-2013'
 'Oct-2007' 'Oct-2009' 'Oct-1997' 'Apr-1980' 'Nov-2014' 'Oct-2013'
 'Nov-1993' 'Jan-2009' 'Jan-1987' 'Jul-1985' 'Nov-2013' 'Jul-1991'
 'Oct-2011' 'Mar-1982' 'Jun-2013' 'Aug-2015' 'Apr-2011' 'May-1998'
 'Apr-1979' 'Jan-1990' 'Feb-2015' 'Jun-1987' 'Nov-2001' 'Apr-1989'
 'Feb-1988' 'Sep-1987' 'May-1997' 'Mar-1995' 'Feb-2000' 'Mar-2014'
 'Mar-2000' 'Oct-2012' 'Jun-1977' 'Sep-2002' 'Jan-1982' 'Dec-2010'
 'Mar-1998' 'Apr-1973' 'Apr-1986' 'May-1985' 'Sep-1988' 'Oct-2015'
 'Mar-1981' 'Jan-1992' 'Feb-1994' 'Aug-1989' 'Jan-2016' 'Jun-1993'
 'Nov-1965' 'Jan-1996' 'Nov-1989' 'Aug-2011' 'Feb-2006' 'Jan-1989'
 'Apr-2015' 'Apr-1994' 'Jun-1996' 'May-1994' 'Apr-1997' 'Dec-1995'
 'Apr-2010' 'Dec-1981' 'Apr-2002' 'Mar-2013' 'Mar-1985' 'Oct-1998'
 'Jan-1991' 'Feb-2014' 'Sep-1996' 'Jan-1995' 'Dec-1989' 'Feb-1998'
 'Mar-1990' 'Aug-1992' 'Nov-2008' 'Nov-1972' 'Aug-1980' 'Nov-1977'
 'Sep-1993' 'Jul-1986' 'May-1986' 'May-1988' 'Jun-1989' 'Jan-1999'
 'May-2011' 'Mar-1999' 'Mar-1977' 'Sep-1989' 'Aug-1988' 'Apr-1977'
 'Mar-1966' 'Sep-2014' 'Feb-1985' 'May-1992' 'Apr-2013' 'Oct-1993'
 'Oct-2004' 'Aug-1972' 'Sep-1990' 'Aug-1991' 'Apr-1988' 'Nov-1986'
 'Dec-1986' 'Feb-1977' 'Oct-1987' 'Dec-2014' 'Nov-2015' 'Oct-1989'
 'Sep-1999' 'Sep-2015' 'Jan-1965' 'Jun-2000' 'Oct-1981' 'Jan-1994'
 'Dec-2015' 'Oct-1983' 'Apr-1967' 'Nov-1976' 'Jan-1998' 'Jul-1994'
 'Apr-1991' 'Jun-2010' 'May-1984' 'Apr-1995' 'Jun-2015' 'Dec-1982'
 'Mar-1984' 'Dec-1997' 'Sep-1992' 'Apr-1987' 'Jan-1984' 'Sep-1995'
 'Feb-2016' 'Nov-1979' 'Mar-1994' 'Sep-1986' 'Nov-1991' 'Apr-1983'
 'Sep-1972' 'Jan-1988' 'Apr-1975' 'Aug-1990' 'Mar-1975' 'Jul-1978'
 'Aug-1984' 'Aug-1982' 'Nov-1974' 'Jul-2014' 'Jun-1990' 'May-1987'
 'Jun-1991' 'Jul-1984' 'Nov-1985' 'Jan-1980' 'Jul-1990' 'Nov-1990'
 'May-1969' 'Feb-1986' 'Sep-1991' 'Aug-1986' 'Aug-1967' 'Sep-1983'
 'Jul-1977' 'Jun-1986' 'Feb-1982' 'Sep-1985' 'Mar-1983' 'Jul-1980'
 'Mar-1972' 'Jan-1983' 'Apr-1981' 'Jul-1971' 'Apr-1978' 'Jan-1981'
 'Jul-1983' 'Feb-1992' 'Nov-1983' 'Nov-1967' 'Oct-1980' 'Jan-1985'
 'Sep-1966' 'May-1982' 'Aug-1981' 'Feb-1990' 'May-1974' 'Nov-1978'
 'Dec-1976' 'Feb-1978' 'Jul-1968' 'Aug-1979' 'Jun-1985' 'May-1980'
 'Dec-1975' 'Mar-1963' 'Apr-1984' 'Jun-1988' 'Nov-1988' 'Dec-1985'
 'Jul-1973' 'Jun-1982' 'Oct-1984' 'Oct-1982' 'Nov-1981' 'Jun-1979'
 'Jun-1978' 'Aug-1978' 'Aug-1971' 'Dec-1988' 'Apr-1982' 'Oct-1988'
 'Oct-1976' 'Sep-1979' 'Feb-1976' 'Oct-1973' 'Apr-1974' 'Feb-1984'
 'Jul-1987' 'Oct-1978' 'Feb-1980' 'Jul-1979' 'Nov-1982' 'Dec-1984'
 'Nov-1971' 'Aug-1985' 'Mar-1973' 'Feb-1981' 'Jan-1979' 'Apr-1985'
 'Sep-1970' 'Apr-1976' 'Feb-1968' 'Apr-1972' 'Oct-1979' 'Mar-1987'
 'Jul-1981' 'May-1966' 'Nov-1984' 'Sep-1976' 'Jun-1973' 'Feb-1969'
 'Jan-1973' 'May-1978' 'Sep-1968' 'Mar-1979' 'Dec-1977' 'Aug-1977'
 'Mar-1976' 'May-1976' 'Aug-1987' 'Jan-1977' 'Feb-1979' 'May-1979'
 'Aug-1965' 'Aug-1964' 'Jan-1970' 'Aug-1983' 'Dec-1978' 'Jan-1969'
 'Feb-1983' 'Aug-1973' 'Sep-1982' 'Aug-1966' 'Sep-1981' 'Dec-1979'
 'Jan-1978' 'Mar-1980' 'May-1973' 'Aug-1974' 'Jan-1974' 'Dec-1980'
 'Sep-1975' 'Dec-1973' 'May-1965' 'Jan-1976' 'Jun-1976' 'Sep-1974'
 'Jul-1969' 'Feb-1972' 'Nov-1973' 'Jun-1980' 'Jun-1974' 'Mar-1970'
 'Oct-1986' 'Jan-1972' 'May-1977' 'Oct-1977' 'Mar-1969' 'Dec-1969'
 'Apr-1968' 'Oct-1966' 'Feb-1970' 'Jul-1976' 'Jul-1972' 'Jan-1967'
 'Jul-1982' 'Jun-1967' 'Jan-1954' 'Oct-1959' 'Aug-1975' 'Feb-1975'
 'Sep-1969' 'Sep-1964' 'Aug-1953' 'Oct-1971' 'Jun-1964' 'Feb-1974'
 'Mar-1978' 'Feb-1961' 'Jun-1972' 'Dec-1974' 'Apr-1971' 'Jul-1970'
 'Oct-1964' 'Feb-1973' 'Aug-1970' 'Dec-1965' 'Jan-1960' 'Jun-1970'
 'Oct-1974' 'Oct-1968' 'Dec-1959' 'Jan-1968' 'Nov-1968' 'Apr-1970'
 'Jan-1944' 'Jul-1975' 'Sep-1965' 'Apr-1957' 'Jun-1961' 'Apr-1969'
 'Jun-1975' 'May-1975' 'Jun-1971' 'May-1970' 'Aug-1976' 'Mar-1968'
 'May-1967' 'Dec-1972' 'May-1963' 'Jul-1959' 'May-1971' 'Nov-1969'
 'Feb-1967' 'Aug-1968' 'Oct-1958' 'Jun-1969' 'Oct-1969' 'Jul-1964'
 'Nov-1959' 'Jun-1981' 'Jan-1963' 'Sep-1973' 'Aug-1969' 'Jun-1968'
 'Oct-1970' 'May-1962' 'Feb-1971' 'May-1972' 'Sep-1961' 'Oct-1956'
 'Jun-1965' 'Oct-1972' 'Feb-1965' 'Jul-1965' 'Nov-1962' 'Dec-1960'
 'Jul-1967' 'Jun-1966' 'Jan-1961' 'Dec-1962' 'Dec-1970' 'Jul-1961'
 'Sep-1967' 'Dec-1971' 'Apr-1966' 'Jan-1971' 'Mar-1971' 'Dec-1964'
 'Jan-1955' 'Sep-1971' 'Apr-1964' 'Nov-1960' 'Jan-1959' 'Nov-1966'
 'May-1961' 'Dec-1968' 'Feb-1966' 'Jan-1951' 'Jan-1964' 'Mar-1967'
 'Jul-1960' 'Jan-1966' 'Apr-1965' 'Jan-1962' 'Apr-1963' 'Mar-1960'
 'Sep-1959' 'Feb-1959' 'Aug-1963' 'Mar-1959']
revol_util: ['19.7%' '87.7%' '77.5%' ... '107.4%' '103.5%' '105.5%']
initial_list_status: ['w' 'f']
last_pymnt_d: [nan 'Apr-2019' 'Mar-2019' 'Feb-2019' 'Jan-2019']
next_pymnt_d: ['Apr-2019' 'May-2019' nan]
last_credit_pull_d: ['Apr-2019' 'Mar-2019' 'Feb-2019' nan 'Jan-2019' 'Dec-2018']
application_type: ['Individual' 'Joint App']
hardship_flag: ['N']
debt_settlement_flag: ['N']

# **Dropping the unnecessary cat Cols:**

In [158]:
df.drop('sub_grade', axis=1, inplace=True)# cause multicollinearity with grade
df.drop('issue_d', axis=1, inplace=True)# loan_term is based on this col, multicolenirity
df.drop('pymnt_plan', axis=1, inplace=True) # signle value n(e.g., 'n' for no payment plan)
df.drop('title', axis=1, inplace=True)# similar to purpose col
df.drop('zip_code', axis=1, inplace=True)  #High cardinality causing difficulty for encoding
df.drop('addr_state', axis=1, inplace=True) # high cardinality and correlated to location
df.drop('earliest_cr_line', axis=1, inplace=True) # multicollinearity with other credit history-related features
df.drop('last_pymnt_d', axis=1, inplace=True) # introduce multicollinearity with other payment date-related features.
df.drop('next_pymnt_d', axis=1, inplace=True)# might have many missing values or introduce multicollinearity with other payment date-related features.
df.drop('last_credit_pull_d', axis=1, inplace=True) #  insignificant addition to the data and multicollinearity with other date-related features

In [180]:
df.drop('hardship_flag', axis=1, inplace=True)
df.drop('debt_settlement_flag', axis=1, inplace=True)

In [160]:
df.shape

(115675, 92)

In [161]:
df.columns

Index(['loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate',
       'installment', 'grade', 'emp_title', 'emp_length', 'home_ownership',
       'annual_inc', 'verification_status', 'loan_status', 'purpose', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'mths_since_last_delinq', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'application_type', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal',
       'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m',
       'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m',
       'open_rv_24m', 'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths', 'avg_cur_bal',
       'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'delinq_amnt',
       'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op',
       'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc',
       'mths_since_recent_inq', 'num_accts_ever_120_pd', 'num_actv_bc_tl',
       'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl',
       'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats',
       'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m',
       'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75',
       'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim',
       'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit',
       'hardship_flag', 'debt_settlement_flag'],
      dtype='object')

In [163]:
df['loan_status'].value_counts()

loan_status
Current               94116
Issued                18835
Fully Paid             2157
In Grace Period         233
Late (16-30 days)       155
Late (31-120 days)      138
Charged Off              41
Name: count, dtype: int64

In [164]:
# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,loan_status,purpose,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
80,35000.0,35000.0,35000.0,60 months,0.1308,797.80,B,PSD Team,< 1 year,MORTGAGE,125890.0,Verified,Fully Paid,debt_consolidation,30.48,0.0,0.0,NaN,14.0,0.0,32363.0,0.667,29.0,w,0.00,0.00,35016.528333,35016.53,35000.00,16.53,0.0,0.0,0.0,35067.40,0.0,1.0,Individual,0.0,69.0,343773.0,0.0,3.0,2.0,3.0,8.0,98987.0,51.0,0.0,0.0,10327.0,61.0,48500.0,0.0,2.0,0.0,3.0,28648.0,5425.0,83.4,0.0,0.0,134.0,139.0,34.0,8.0,6.0,34.0,23.0,0.0,5.0,6.0,6.0,6.0,12.0,10.0,11.0,6.0,14.0,0.0,0.0,0.0,2.0,100.0,80.0,0.0,0.0,399376.0,131350.0,32700.0,130876.0,N,N
82,20000.0,20000.0,20000.0,36 months,0.2250,769.00,D,Human Resources Liaison,10+ years,RENT,75000.0,Not Verified,Current,debt_consolidation,24.37,0.0,0.0,NaN,8.0,0.0,44934.0,0.956,11.0,w,19431.00,19431.00,719.000000,719.00,569.00,150.00,0.0,0.0,0.0,769.00,0.0,1.0,Individual,0.0,0.0,55014.0,0.0,2.0,0.0,0.0,50.0,10080.0,33.0,1.0,1.0,18068.0,71.0,47000.0,0.0,0.0,0.0,1.0,6877.0,2066.0,95.6,0.0,0.0,177.0,199.0,12.0,12.0,0.0,12.0,NaN,0.0,6.0,6.0,6.0,7.0,4.0,6.0,7.0,6.0,8.0,0.0,0.0,0.0,1.0,100.0,100.0,0.0,0.0,77797.0,55014.0,47000.0,30797.0,N,N
93,10500.0,10500.0,10500.0,36 months,0.1719,375.35,C,Transportation Coordinator,9 years,RENT,66000.0,Source Verified,Current,debt_consolidation,27.24,0.0,0.0,34.0,8.0,0.0,1609.0,0.435,14.0,w,10204.87,10204.87,355.290000,355.29,295.13,60.16,0.0,0.0,0.0,375.35,0.0,1.0,Individual,0.0,178.0,38199.0,3.0,4.0,2.0,4.0,3.0,36590.0,59.0,1.0,2.0,1553.0,58.0,3700.0,1.0,0.0,4.0,6.0,4775.0,447.0,77.7,0.0,0.0,93.0,96.0,3.0,3.0,0.0,20.0,1.0,0.0,1.0,2.0,1.0,1.0,10.0,3.0,3.0,2.0,8.0,0.0,0.0,0.0,3.0,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
99,25000.0,25000.0,25000.0,36 months,0.2000,929.09,D,Engineer,8 years,MORTGAGE,105000.0,Verified,Current,debt_consolidation,20.23,0.0,0.0,50.0,17.0,1.0,18368.0,0.364,34.0,w,24293.13,24293.13,873.530000,873.53,706.87,166.66,0.0,0.0,0.0,929.09,0.0,1.0,Individual,0.0,165.0,228119.0,3.0,3.0,2.0,3.0,4.0,42273.0,86.0,4.0,8.0,5197.0,61.0,50400.0,4.0,9.0,3.0,13.0,13419.0,29502.0,28.4,0.0,0.0,87.0,286.0,1.0,1.0,2.0,1.0,11.0,3.0,7.0,11.0,8.0,13.0,14.0,13.0,18.0,11.0,17.0,0.0,0.0,0.0,6.0,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
132,20000.0,20000.0,20000.0,60 months,0.2000,529.88,D,NaN,NaN,MORTGAGE,56000.0,Verified,Current,credit_card,24.26,0.0,0.0,66.0,8.0,0.0,13247.0,0.757,21.0,w,19636.79,19636.79,485.440000,485.44,363.21,122.23,0.0,0.0,0.0,529.88,0.0,1.0,Individual,0.0,0.0,45684.0,2.0,3.0,2.0,3.0,4.0,32437.0,75.0,2.0,3.0,2810.0,75.0,17500.0,0.0,4.0,1.0,6.0,5711.0,2839.0,62.1,0.0,0.0,159.0,156.0,7.0,4.0,0.0,7.0,7.0,6.0,2.0,5.0,2.0,7.0,8.0,5.0,13.0,5.0,8.0,0.0,0.0,0.0,4.0,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N

# **Reducing the uniqe values in emp_title col:**

In [162]:
# convert interest and revol_util rate to float
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100

df['revol_util'] = df['revol_util'].str.replace('%', '')
df['revol_util'] = df['revol_util'].astype('float') / 100

In [165]:
df.columns = df.columns.str.strip()

In [166]:
# Step 1: Remove ' months' string
df['term'] = df['term'].str.replace(' months', '')

# Step 2: Trim whitespace (if any)
df['term'] = df['term'].str.strip()

# Step 3: Replace empty strings with NaN and drop them
df['term'].replace('', float('NaN'), inplace=True)
df.dropna(subset=['term'], inplace=True)

# Step 4: Convert to integers
df['term'] = df['term'].astype(int)

In [167]:
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,loan_status,purpose,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
80,35000.0,35000.0,35000.0,60,0.1308,797.80,B,PSD Team,< 1 year,MORTGAGE,125890.0,Verified,Fully Paid,debt_consolidation,30.48,0.0,0.0,NaN,14.0,0.0,32363.0,0.667,29.0,w,0.00,0.00,35016.528333,35016.53,35000.00,16.53,0.0,0.0,0.0,35067.40,0.0,1.0,Individual,0.0,69.0,343773.0,0.0,3.0,2.0,3.0,8.0,98987.0,51.0,0.0,0.0,10327.0,61.0,48500.0,0.0,2.0,0.0,3.0,28648.0,5425.0,83.4,0.0,0.0,134.0,139.0,34.0,8.0,6.0,34.0,23.0,0.0,5.0,6.0,6.0,6.0,12.0,10.0,11.0,6.0,14.0,0.0,0.0,0.0,2.0,100.0,80.0,0.0,0.0,399376.0,131350.0,32700.0,130876.0,N,N
82,20000.0,20000.0,20000.0,36,0.2250,769.00,D,Human Resources Liaison,10+ years,RENT,75000.0,Not Verified,Current,debt_consolidation,24.37,0.0,0.0,NaN,8.0,0.0,44934.0,0.956,11.0,w,19431.00,19431.00,719.000000,719.00,569.00,150.00,0.0,0.0,0.0,769.00,0.0,1.0,Individual,0.0,0.0,55014.0,0.0,2.0,0.0,0.0,50.0,10080.0,33.0,1.0,1.0,18068.0,71.0,47000.0,0.0,0.0,0.0,1.0,6877.0,2066.0,95.6,0.0,0.0,177.0,199.0,12.0,12.0,0.0,12.0,NaN,0.0,6.0,6.0,6.0,7.0,4.0,6.0,7.0,6.0,8.0,0.0,0.0,0.0,1.0,100.0,100.0,0.0,0.0,77797.0,55014.0,47000.0,30797.0,N,N
93,10500.0,10500.0,10500.0,36,0.1719,375.35,C,Transportation Coordinator,9 years,RENT,66000.0,Source Verified,Current,debt_consolidation,27.24,0.0,0.0,34.0,8.0,0.0,1609.0,0.435,14.0,w,10204.87,10204.87,355.290000,355.29,295.13,60.16,0.0,0.0,0.0,375.35,0.0,1.0,Individual,0.0,178.0,38199.0,3.0,4.0,2.0,4.0,3.0,36590.0,59.0,1.0,2.0,1553.0,58.0,3700.0,1.0,0.0,4.0,6.0,4775.0,447.0,77.7,0.0,0.0,93.0,96.0,3.0,3.0,0.0,20.0,1.0,0.0,1.0,2.0,1.0,1.0,10.0,3.0,3.0,2.0,8.0,0.0,0.0,0.0,3.0,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
99,25000.0,25000.0,25000.0,36,0.2000,929.09,D,Engineer,8 years,MORTGAGE,105000.0,Verified,Current,debt_consolidation,20.23,0.0,0.0,50.0,17.0,1.0,18368.0,0.364,34.0,w,24293.13,24293.13,873.530000,873.53,706.87,166.66,0.0,0.0,0.0,929.09,0.0,1.0,Individual,0.0,165.0,228119.0,3.0,3.0,2.0,3.0,4.0,42273.0,86.0,4.0,8.0,5197.0,61.0,50400.0,4.0,9.0,3.0,13.0,13419.0,29502.0,28.4,0.0,0.0,87.0,286.0,1.0,1.0,2.0,1.0,11.0,3.0,7.0,11.0,8.0,13.0,14.0,13.0,18.0,11.0,17.0,0.0,0.0,0.0,6.0,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
132,20000.0,20000.0,20000.0,60,0.2000,529.88,D,NaN,NaN,MORTGAGE,56000.0,Verified,Current,credit_card,24.26,0.0,0.0,66.0,8.0,0.0,13247.0,0.757,21.0,w,19636.79,19636.79,485.440000,485.44,363.21,122.23,0.0,0.0,0.0,529.88,0.0,1.0,Individual,0.0,0.0,45684.0,2.0,3.0,2.0,3.0,4.0,32437.0,75.0,2.0,3.0,2810.0,75.0,17500.0,0.0,4.0,1.0,6.0,5711.0,2839.0,62.1,0.0,0.0,159.0,156.0,7.0,4.0,0.0,7.0,7.0,6.0,2.0,5.0,2.0,7.0,8.0,5.0,13.0,5.0,8.0,0.0,0.0,0.0,4.0,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N

In [168]:
df['term'].dtype

dtype('int64')

E**xploratory Data Analysis (EDA) phase.** It involves processes like handling missing values, detecting and correcting errors, and ensuring that the data is in a suitable format for analysis and modeling.

# **Imputing the NAN values:**

In [173]:
from sklearn.impute import SimpleImputer

# Separate numerical and categorical columns
numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns
numerical_cols = numerical_cols.drop('mths_since_last_delinq')

categorical_cols = df.select_dtypes(include=['object']).columns

In [174]:
# Impute low missing value columns for numerical data
num_imputer = SimpleImputer(strategy='mean')
df[numerical_cols] = num_imputer.fit_transform(df[numerical_cols])

# Impute low missing value columns for categorical data
cat_imputer = SimpleImputer(strategy='most_frequent')
df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])

In [176]:
df.isna().sum()

loan_amnt                         0
funded_amnt                       0
funded_amnt_inv                   0
term                              0
int_rate                          0
installment                       0
grade                             0
emp_title                         0
emp_length                        0
home_ownership                    0
annual_inc                        0
verification_status               0
loan_status                       0
purpose                           0
dti                               0
delinq_2yrs                       0
inq_last_6mths                    0
mths_since_last_delinq        55177
open_acc                          0
pub_rec                           0
revol_bal                         0
revol_util                        0
total_acc                         0
initial_list_status               0
out_prncp                         0
out_prncp_inv                     0
total_pymnt                       0
total_pymnt_inv                   0
total_rec_prncp                   0
total_rec_int                     0
total_rec_late_fee                0
recoveries                        0
collection_recovery_fee           0
last_pymnt_amnt                   0
collections_12_mths_ex_med        0
policy_code                       0
application_type                  0
acc_now_delinq                    0
tot_coll_amt                      0
tot_cur_bal                       0
open_acc_6m                       0
open_act_il                       0
open_il_12m                       0
open_il_24m                       0
mths_since_rcnt_il                0
total_bal_il                      0
il_util                           0
open_rv_12m                       0
open_rv_24m                       0
max_bal_bc                        0
all_util                          0
total_rev_hi_lim                  0
inq_fi                            0
total_cu_tl                       0
inq_last_12m                      0
acc_open_past_24mths              0
avg_cur_bal                       0
bc_open_to_buy                    0
bc_util                           0
chargeoff_within_12_mths          0
delinq_amnt                       0
mo_sin_old_il_acct                0
mo_sin_old_rev_tl_op              0
mo_sin_rcnt_rev_tl_op             0
mo_sin_rcnt_tl                    0
mort_acc                          0
mths_since_recent_bc              0
mths_since_recent_inq             0
num_accts_ever_120_pd             0
num_actv_bc_tl                    0
num_actv_rev_tl                   0
num_bc_sats                       0
num_bc_tl                         0
num_il_tl                         0
num_op_rev_tl                     0
num_rev_accts                     0
num_rev_tl_bal_gt_0               0
num_sats                          0
num_tl_120dpd_2m                  0
num_tl_30dpd                      0
num_tl_90g_dpd_24m                0
num_tl_op_past_12m                0
pct_tl_nvr_dlq                    0
percent_bc_gt_75                  0
pub_rec_bankruptcies              0
tax_liens                         0
tot_hi_cred_lim                   0
total_bal_ex_mort                 0
total_bc_limit                    0
total_il_high_credit_limit        0
hardship_flag                     0
debt_settlement_flag              0
dtype: int64

# **Imputing mths_since_last_delinq col with KNNImputer as it has more than 50% nan values:**

In [177]:
from sklearn.impute import KNNImputer
# Use KNNImputer to impute 'mths_since_last_delinq'
knn_imputer = KNNImputer(n_neighbors=5)
df['mths_since_last_delinq']= knn_imputer.fit_transform( df[['mths_since_last_delinq']])

In [178]:
df['mths_since_last_delinq'].isna().sum()

0

# **Featuring Engineering:**

# **Recuding the unique values in grade col:**

In [201]:
# Assuming df is your DataFrame
grade_map = {
    'A': 'A',
    'B': 'A',
    'C': 'B',
    'D': 'B',
    'E': 'C',
    'F': 'C',
    'G': 'C'
    }

df['grade'] = df['grade'].map(grade_map)

In [202]:
df['grade'].value_counts()

grade
A    58991
B    34482
C     3367
Name: count, dtype: int64

# **Reducing the uniqe values in emp_title col:**

In [169]:
# Define thresholds based on overall median income
overall_median_income = df['annual_inc'].median()
low_income_threshold = overall_median_income / 2
high_income_threshold = overall_median_income * 1.5


# Create a function to categorize jobs based on income
def categorize_job(title):
    annual_income = df[df['emp_title'] == title]['annual_inc'].mean()# mean of annual_inc after filtering according to the given job title
    if annual_income < low_income_threshold:
        return 'low_income_job'
    elif annual_income < high_income_threshold:
        return 'moderate_income_job'
    else:
        return 'high_income_job'

# Apply the categorization to the 'emp_title' column
df['emp_title'] = df['emp_title'].apply(categorize_job)

# **Reducing the uniqe values in emp_length col:**

In [188]:
# Create a function to categorize employment length
def categorize_emp_length(length):
    if length == '< 1 year' or length == '1 year':
        return 'short'
    elif length in ['2 years', '3 years', '4 years', '5 years']:
        return 'medium'
    else:
        return 'long'

# Apply the categorization to the 'emp_length' column
df['emp_length'] = df['emp_length'].apply(categorize_emp_length)

# **Reducing the uniqe values in home_ownership col:**

In [191]:
# replacing 'ANY', 'NONE' by 'RENT'
df['home_ownership'].replace(['ANY', 'NONE'], 'RENT', inplace=True)

In [192]:
df.home_ownership.value_counts()

home_ownership
MORTGAGE    48791
RENT        36943
OWN         11106
Name: count, dtype: int64

# **Reducing the uniqe values in verification_status col:**

In [194]:
# replacing 'Source Verified'by 'Verified'
df['verification_status'].replace('Source Verified', 'Verified', inplace=True)

In [195]:
df['verification_status'].value_counts()

verification_status
Verified        50665
Not Verified    46175
Name: count, dtype: int64

# **Reducing the uniqe values in purpose col:**

purpose: ['debt_consolidation' 'credit_card' 'other' 'home_improvement' 'car'
 'major_purchase' 'moving' 'house' 'small_business' 'medical' 'vacation'
 'renewable_energy']

In [196]:
purpose_map = {
    'debt_consolidation': 'medium',
    'credit_card': 'short',
    'other': 'medium',
    'home_improvement': 'medium',
    'car': 'short',
    'major_purchase': 'medium',
    'moving': 'short',
    'house': 'long',
    'small_business': 'long',
    'medical': 'medium',
    'vacation': 'short',
    'renewable_energy': 'long'
}

df['purpose'] = df['purpose'].map(purpose_map)

In [197]:
df.purpose.value_counts()

purpose
medium    66538
short     28719
long       1583
Name: count, dtype: int64

# **Reducing the uniqe values in loan_status  target variable col:**

In [ ]:
loan_status: ['Fully Paid' 'Current' 'Charged Off' 'In Grace Period'
 'Late (16-30 days)' 'Late (31-120 days)']

In [193]:
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,loan_status,purpose,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
80,35000.0,35000.0,35000.0,60.0,0.1308,797.80,B,high_income_job,long,MORTGAGE,125890.0,Verified,Fully Paid,debt_consolidation,30.48,0.0,0.0,36.674291,14.0,0.0,32363.0,0.667,29.0,w,0.00,0.00,35016.528333,35016.53,35000.00,16.53,0.0,0.0,0.0,35067.40,0.0,1.0,Individual,0.0,69.0,343773.0,0.0,3.0,2.0,3.0,8.0,98987.0,51.0,0.0,0.0,10327.0,61.0,48500.0,0.0,2.0,0.0,3.0,28648.0,5425.0,83.4,0.0,0.0,134.0,139.0,34.0,8.0,6.0,34.0,23.000000,0.0,5.0,6.0,6.0,6.0,12.0,10.0,11.0,6.0,14.0,0.0,0.0,0.0,2.0,100.0,80.0,0.0,0.0,399376.0,131350.0,32700.0,130876.0
82,20000.0,20000.0,20000.0,36.0,0.2250,769.00,D,moderate_income_job,long,RENT,75000.0,Not Verified,Current,debt_consolidation,24.37,0.0,0.0,36.674291,8.0,0.0,44934.0,0.956,11.0,w,19431.00,19431.00,719.000000,719.00,569.00,150.00,0.0,0.0,0.0,769.00,0.0,1.0,Individual,0.0,0.0,55014.0,0.0,2.0,0.0,0.0,50.0,10080.0,33.0,1.0,1.0,18068.0,71.0,47000.0,0.0,0.0,0.0,1.0,6877.0,2066.0,95.6,0.0,0.0,177.0,199.0,12.0,12.0,0.0,12.0,7.681702,0.0,6.0,6.0,6.0,7.0,4.0,6.0,7.0,6.0,8.0,0.0,0.0,0.0,1.0,100.0,100.0,0.0,0.0,77797.0,55014.0,47000.0,30797.0
93,10500.0,10500.0,10500.0,36.0,0.1719,375.35,C,moderate_income_job,long,RENT,66000.0,Source Verified,Current,debt_consolidation,27.24,0.0,0.0,34.000000,8.0,0.0,1609.0,0.435,14.0,w,10204.87,10204.87,355.290000,355.29,295.13,60.16,0.0,0.0,0.0,375.35,0.0,1.0,Individual,0.0,178.0,38199.0,3.0,4.0,2.0,4.0,3.0,36590.0,59.0,1.0,2.0,1553.0,58.0,3700.0,1.0,0.0,4.0,6.0,4775.0,447.0,77.7,0.0,0.0,93.0,96.0,3.0,3.0,0.0,20.0,1.000000,0.0,1.0,2.0,1.0,1.0,10.0,3.0,3.0,2.0,8.0,0.0,0.0,0.0,3.0,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0
99,25000.0,25000.0,25000.0,36.0,0.2000,929.09,D,high_income_job,long,MORTGAGE,105000.0,Verified,Current,debt_consolidation,20.23,0.0,0.0,50.000000,17.0,1.0,18368.0,0.364,34.0,w,24293.13,24293.13,873.530000,873.53,706.87,166.66,0.0,0.0,0.0,929.09,0.0,1.0,Individual,0.0,165.0,228119.0,3.0,3.0,2.0,3.0,4.0,42273.0,86.0,4.0,8.0,5197.0,61.0,50400.0,4.0,9.0,3.0,13.0,13419.0,29502.0,28.4,0.0,0.0,87.0,286.0,1.0,1.0,2.0,1.0,11.000000,3.0,7.0,11.0,8.0,13.0,14.0,13.0,18.0,11.0,17.0,0.0,0.0,0.0,6.0,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0
132,20000.0,20000.0,20000.0,60.0,0.2000,529.88,D,high_income_job,long,MORTGAGE,56000.0,Verified,Current,credit_card,24.26,0.0,0.0,66.000000,8.0,0.0,13247.0,0.757,21.0,w,19636.79,19636.79,485.440000,485.44,363.21,122.23,0.0,0.0,0.0,529.88,0.0,1.0,Individual,0.0,0.0,45684.0,2.0,3.0,2.0,3.0,4.0,32437.0,75.0,2.0,3.0,2810.0,75.0,17500.0,0.0,4.0,1.0,6.0,5711.0,2839.0,62.1,0.0,0.0,159.0,156.0,7.0,4.0,0.0,7.0,7.000000,6.0,2.0,5.0,2.0,7.0,8.0,5.0,13.0,5.0,8.0,0.0,0.0,0.0,4.0,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0

In [203]:
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    print(f"{col}: {df[col].unique()}")

grade: ['A' 'B' 'C']
emp_title: ['high_income_job' 'moderate_income_job' 'low_income_job']
emp_length: ['long']
home_ownership: ['MORTGAGE' 'RENT' 'OWN']
verification_status: ['Verified' 'Not Verified']
loan_status: ['Low Risk' 'High Risk' 'Medium Risk']
purpose: ['medium' 'short' 'long']
initial_list_status: ['w' 'f']
application_type: ['Individual' 'Joint App']

# **Feature Engineering on Target Variable:**

In [ ]:
# Checking the subclass of dependent variable ["loan_status"]
print(df['loan_status'].value_counts())

loan_status
Current               94116
Fully Paid             2157
In Grace Period         233
Late (16-30 days)       155
Late (31-120 days)      138
Charged Off              41
Name: count, dtype: int64

In [198]:
# Create a mapping dictionary for loan_status to risk categories
status_mapping = {
    'Current': 'Low Risk',
    'Fully Paid': 'Low Risk',
    'In Grace Period': 'Medium Risk',
    'Late (16-30 days)': 'Medium Risk',
    'Late (31-120 days)': 'High Risk',
    'Charged Off': 'High Risk'
}

# Apply the mapping to create a new column 'risk_category'
df['loan_status'] = df['loan_status'].map(status_mapping)

In [199]:
df['loan_status'].value_counts()

loan_status
Low Risk       96273
Medium Risk      388
High Risk        179
Name: count, dtype: int64

In [200]:
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,loan_status,purpose,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
80,35000.0,35000.0,35000.0,60.0,0.1308,797.80,B,high_income_job,long,MORTGAGE,125890.0,Verified,Low Risk,medium,30.48,0.0,0.0,36.674291,14.0,0.0,32363.0,0.667,29.0,w,0.00,0.00,35016.528333,35016.53,35000.00,16.53,0.0,0.0,0.0,35067.40,0.0,1.0,Individual,0.0,69.0,343773.0,0.0,3.0,2.0,3.0,8.0,98987.0,51.0,0.0,0.0,10327.0,61.0,48500.0,0.0,2.0,0.0,3.0,28648.0,5425.0,83.4,0.0,0.0,134.0,139.0,34.0,8.0,6.0,34.0,23.000000,0.0,5.0,6.0,6.0,6.0,12.0,10.0,11.0,6.0,14.0,0.0,0.0,0.0,2.0,100.0,80.0,0.0,0.0,399376.0,131350.0,32700.0,130876.0
82,20000.0,20000.0,20000.0,36.0,0.2250,769.00,D,moderate_income_job,long,RENT,75000.0,Not Verified,Low Risk,medium,24.37,0.0,0.0,36.674291,8.0,0.0,44934.0,0.956,11.0,w,19431.00,19431.00,719.000000,719.00,569.00,150.00,0.0,0.0,0.0,769.00,0.0,1.0,Individual,0.0,0.0,55014.0,0.0,2.0,0.0,0.0,50.0,10080.0,33.0,1.0,1.0,18068.0,71.0,47000.0,0.0,0.0,0.0,1.0,6877.0,2066.0,95.6,0.0,0.0,177.0,199.0,12.0,12.0,0.0,12.0,7.681702,0.0,6.0,6.0,6.0,7.0,4.0,6.0,7.0,6.0,8.0,0.0,0.0,0.0,1.0,100.0,100.0,0.0,0.0,77797.0,55014.0,47000.0,30797.0
93,10500.0,10500.0,10500.0,36.0,0.1719,375.35,C,moderate_income_job,long,RENT,66000.0,Verified,Low Risk,medium,27.24,0.0,0.0,34.000000,8.0,0.0,1609.0,0.435,14.0,w,10204.87,10204.87,355.290000,355.29,295.13,60.16,0.0,0.0,0.0,375.35,0.0,1.0,Individual,0.0,178.0,38199.0,3.0,4.0,2.0,4.0,3.0,36590.0,59.0,1.0,2.0,1553.0,58.0,3700.0,1.0,0.0,4.0,6.0,4775.0,447.0,77.7,0.0,0.0,93.0,96.0,3.0,3.0,0.0,20.0,1.000000,0.0,1.0,2.0,1.0,1.0,10.0,3.0,3.0,2.0,8.0,0.0,0.0,0.0,3.0,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0
99,25000.0,25000.0,25000.0,36.0,0.2000,929.09,D,high_income_job,long,MORTGAGE,105000.0,Verified,Low Risk,medium,20.23,0.0,0.0,50.000000,17.0,1.0,18368.0,0.364,34.0,w,24293.13,24293.13,873.530000,873.53,706.87,166.66,0.0,0.0,0.0,929.09,0.0,1.0,Individual,0.0,165.0,228119.0,3.0,3.0,2.0,3.0,4.0,42273.0,86.0,4.0,8.0,5197.0,61.0,50400.0,4.0,9.0,3.0,13.0,13419.0,29502.0,28.4,0.0,0.0,87.0,286.0,1.0,1.0,2.0,1.0,11.000000,3.0,7.0,11.0,8.0,13.0,14.0,13.0,18.0,11.0,17.0,0.0,0.0,0.0,6.0,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0
132,20000.0,20000.0,20000.0,60.0,0.2000,529.88,D,high_income_job,long,MORTGAGE,56000.0,Verified,Low Risk,short,24.26,0.0,0.0,66.000000,8.0,0.0,13247.0,0.757,21.0,w,19636.79,19636.79,485.440000,485.44,363.21,122.23,0.0,0.0,0.0,529.88,0.0,1.0,Individual,0.0,0.0,45684.0,2.0,3.0,2.0,3.0,4.0,32437.0,75.0,2.0,3.0,2810.0,75.0,17500.0,0.0,4.0,1.0,6.0,5711.0,2839.0,62.1,0.0,0.0,159.0,156.0,7.0,4.0,0.0,7.0,7.000000,6.0,2.0,5.0,2.0,7.0,8.0,5.0,13.0,5.0,8.0,0.0,0.0,0.0,4.0,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0

# **Encode the categorical variables:**

# **Next steps:**

Handle Imbalanced Data: Consider techniques like oversampling the minority classes ('Medium Risk' and 'High Risk') or undersampling the majority class ('Low Risk') to balance the dataset.

Model Selection: Choose appropriate classification models that handle imbalanced data well, such as Random Forest, Gradient Boosting Machines (GBM), or XGBoost.

Evaluation Metrics: Use evaluation metrics suited for imbalanced datasets, such as precision, recall, F1-score, and ROC AUC.

Cross-Validation: Perform cross-validation to ensure the model's performance is consistent across different subsets of the data.

Hyperparameter Tuning: Optimize model performance through hyperparameter tuning.

term : [' 60 months' ' 36 months']
grade : ['B' 'D' 'C' 'A' 'E' 'F' 'G']
sub_grade : ['B5' 'D3' 'C5' 'D2' 'C4' 'C2' 'D5' 'A3' 'D1' 'C3' 'B2' 'A5' 'A4' 'C1'
 'B3' 'A2' 'B1' 'A1' 'B4' 'D4' 'E3' 'E5' 'E1' 'E4' 'F1' 'E2' 'F4' 'F5'
 'F2' 'F3' 'G3' 'G2' 'G1']
emp_title : ['PSD Team ' 'Human Resources Liaison ' 'Transportation Coordinator ' ...
 'President - North America' 'Estimator/Supervisor' 'sr register csa']
emp_length : ['< 1 year' '10+ years' '9 years' '8 years' '3 years' '6 years' '1 year'
 '7 years' '2 years' '4 years' '5 years']
home_ownership : ['MORTGAGE' 'RENT' 'OWN' 'ANY' 'NONE']
verification_status : ['Verified' 'Not Verified' 'Source Verified']
issue_d : ['Mar-2019' 'Feb-2019' 'Jan-2019']
loan_status : ['Fully Paid' 'Current' 'Charged Off' 'In Grace Period'
 'Late (16-30 days)' 'Late (31-120 days)']
pymnt_plan : ['n']
purpose : ['debt_consolidation' 'credit_card' 'other' 'home_improvement' 'car'
 'major_purchase' 'moving' 'house' 'small_business' 'medical' 'vacation'
 'renewable_energy']
title : ['Debt consolidation' 'Credit card refinancing' 'Other' 'Home improvement'
 'Car financing' 'Major purchase' 'Moving and relocation' 'Home buying'
 'Business' 'Medical expenses' 'Vacation' 'Green loan']
zip_code : ['240xx' '957xx' '765xx' '581xx' '207xx' '450xx' '300xx' '441xx' '596xx'
 '034xx' '958xx' '900xx' '119xx' '208xx' '282xx' '100xx' '760xx' '206xx'
 '076xx' '926xx' '117xx' '283xx' '347xx' '330xx' '773xx' '972xx' '681xx'
 '201xx' '352xx' '923xx' '852xx' '809xx' '243xx' '337xx' '751xx' '385xx'
 '967xx' '327xx' '302xx' '921xx' '189xx' '142xx' '646xx' '907xx' '037xx'
 '073xx' '897xx' '281xx' '606xx' '906xx' '722xx' '053xx' '064xx' '191xx'
 '890xx' '331xx' '481xx' '219xx' '790xx' '495xx' '990xx' '111xx' '085xx'
 '761xx' '370xx' '530xx' '346xx' '133xx' '940xx' '232xx' '554xx' '941xx'
 '222xx' '723xx' '301xx' '329xx' '223xx' '272xx' '560xx' '230xx' '052xx'
 '452xx' '549xx' '442xx' '766xx' '608xx' '010xx' '784xx' '186xx' '980xx'
 '787xx' '557xx' '770xx' '853xx' '799xx' '726xx' '622xx' '973xx' '328xx'
 '130xx' '015xx' '021xx' '660xx' '604xx' '759xx' '373xx' '786xx' '793xx'
 '380xx' '174xx' '925xx' '913xx' '802xx' '393xx' '212xx' '284xx' '335xx'
 '078xx' '342xx' '640xx' '928xx' '104xx' '231xx' '017xx' '030xx' '018xx'
 '432xx' '871xx' '945xx' '762xx' '856xx' '934xx' '731xx' '752xx' '088xx'
 '750xx' '499xx' '402xx' '070xx' '708xx' '810xx' '531xx' '532xx' '496xx'
 '115xx' '748xx' '294xx' '970xx' '423xx' '322xx' '433xx' '600xx' '014xx'
 '981xx' '850xx' '044xx' '334xx' '992xx' '672xx' '238xx' '705xx' '190xx'
 '463xx' '168xx' '458xx' '935xx' '553xx' '177xx' '781xx' '244xx' '061xx'
 '956xx' '551xx' '815xx' '917xx' '720xx' '734xx' '049xx' '165xx' '068xx'
 '741xx' '307xx' '405xx' '211xx' '313xx' '782xx' '062xx' '145xx' '124xx'
 '805xx' '306xx' '305xx' '170xx' '372xx' '356xx' '631xx' '984xx' '183xx'
 '287xx' '769xx' '371xx' '974xx' '775xx' '038xx' '431xx' '325xx' '349xx'
 '490xx' '824xx' '774xx' '881xx' '199xx' '618xx' '605xx' '494xx' '922xx'
 '480xx' '303xx' '087xx' '033xx' '785xx' '261xx' '436xx' '314xx' '210xx'
 '273xx' '275xx' '295xx' '083xx' '880xx' '374xx' '467xx' '234xx' '905xx'
 '937xx' '453xx' '914xx' '630xx' '543xx' '276xx' '491xx' '959xx' '407xx'
 '563xx' '067xx' '140xx' '113xx' '154xx' '707xx' '920xx' '032xx' '933xx'
 '627xx' '351xx' '377xx' '156xx' '598xx' '321xx' '691xx' '756xx' '780xx'
 '427xx' '245xx' '224xx' '132xx' '740xx' '027xx' '279xx' '109xx' '326xx'
 '953xx' '460xx' '396xx' '333xx' '267xx' '270xx' '800xx' '561xx' '298xx'
 '105xx' '315xx' '982xx' '233xx' '462xx' '638xx' '728xx' '457xx' '486xx'
 '440xx' '997xx' '895xx' '902xx' '597xx' '197xx' '482xx' '712xx' '746xx'
 '757xx' '489xx' '421xx' '978xx' '435xx' '665xx' '704xx' '891xx' '026xx'
 '546xx' '951xx' '801xx' '074xx' '995xx' '112xx' '483xx' '339xx' '360xx'
 '180xx' '319xx' '674xx' '633xx' '471xx' '194xx' '662xx' '254xx' '350xx'
 '946xx' '336xx' '080xx' '103xx' '703xx' '445xx' '535xx' '706xx' '271xx'
 '550xx' '152xx' '114xx' '989xx' '574xx' '657xx' '195xx' '320xx' '468xx'
 '601xx' '366xx' '954xx' '278xx' '386xx' '548xx' '859xx' '996xx' '730xx'
 '908xx' '916xx' '487xx' '968xx' '420xx' '637xx' '636xx' '285xx' '389xx'
 '430xx' '944xx' '020xx' '216xx' '936xx' '310xx' '610xx' '394xx' '952xx'
 '541xx' '451xx' '454xx' '308xx' '025xx' '296xx' '042xx' '221xx' '317xx'
 '128xx' '910xx' '390xx' '628xx' '121xx' '158xx' '625xx' '368xx' '993xx'
 '391xx' '865xx' '812xx' '558xx' '323xx' '975xx' '217xx' '701xx' '081xx'
 '855xx' '422xx' '280xx' '882xx' '126xx' '641xx' '493xx' '719xx' '932xx'
 '362xx' '931xx' '629xx' '341xx' '193xx' '898xx' '376xx' '564xx' '950xx'
 '840xx' '338xx' '912xx' '274xx' '367xx' '586xx' '988xx' '919xx' '200xx'
 '150xx' '829xx' '054xx' '290xx' '173xx' '107xx' '312xx' '721xx' '685xx'
 '534xx' '983xx' '797xx' '473xx' '611xx' '144xx' '577xx' '439xx' '652xx'
 '559xx' '448xx' '461xx' '110xx' '209xx' '492xx' '986xx' '148xx' '381xx'
 '286xx' '292xx' '794xx' '022xx' '903xx' '648xx' '146xx' '619xx' '029xx'
 '227xx' '930xx' '985xx' '079xx' '791xx' '833xx' '357xx' '677xx' '863xx'
 '028xx' '595xx' '410xx' '857xx' '864xx' '874xx' '806xx' '727xx' '013xx'
 '159xx' '120xx' '383xx' '344xx' '288xx' '065xx' '894xx' '082xx' '291xx'
 '955xx' '108xx' '749xx' '948xx' '089xx' '106xx' '498xx' '668xx' '754xx'
 '836xx' '118xx' '844xx' '384xx' '354xx' '475xx' '225xx' '825xx' '392xx'
 '299xx' '072xx' '545xx' '939xx' '131xx' '778xx' '798xx' '455xx' '235xx'
 '562xx' '444xx' '395xx' '024xx' '086xx' '795xx' '226xx' '198xx' '599xx'
 '160xx' '136xx' '949xx' '398xx' '671xx' '401xx' '101xx' '166xx' '446xx'
 '265xx' '592xx' '379xx' '904xx' '700xx' '738xx' '297xx' '123xx' '615xx'
 '924xx' '947xx' '626xx' '971xx' '228xx' '122xx' '324xx' '161xx' '066xx'
 '023xx' '063xx' '540xx' '293xx' '472xx' '488xx' '873xx' '851xx' '547xx'
 '019xx' '745xx' '737xx' '977xx' '469xx' '236xx' '127xx' '155xx' '645xx'
 '788xx' '465xx' '361xx' '693xx' '135xx' '011xx' '229xx' '474xx' '792xx'
 '153xx' '171xx' '585xx' '537xx' '612xx' '613xx' '182xx' '141xx' '711xx'
 '060xx' '046xx' '218xx' '012xx' '125xx' '713xx' '400xx' '249xx' '837xx'
 '675xx' '242xx' '571xx' '434xx' '783xx' '658xx' '424xx' '175xx' '260xx'
 '039xx' '667xx' '147xx' '776xx' '031xx' '724xx' '071xx' '544xx' '485xx'
 '438xx' '057xx' '241xx' '069xx' '411xx' '838xx' '655xx' '758xx' '437xx'
 '077xx' '413xx' '670xx' '763xx' '834xx' '220xx' '860xx' '058xx' '768xx'
 '616xx' '277xx' '666xx' '251xx' '624xx' '257xx' '767xx' '927xx' '789xx'
 '803xx' '237xx' '991xx' '359xx' '138xx' '680xx' '417xx' '035xx' '456xx'
 '382xx' '484xx' '043xx' '129xx' '609xx' '656xx' '476xx' '172xx' '570xx'
 '814xx' '717xx' '179xx' '807xx' '464xx' '184xx' '875xx' '779xx' '620xx'
 '255xx' '676xx' '804xx' '678xx' '725xx' '943xx' '847xx' '915xx' '102xx'
 '661xx' '714xx' '188xx' '151xx' '976xx' '176xx' '870xx' '358xx' '580xx'
 '378xx' '388xx' '591xx' '539xx' '040xx' '764xx' '163xx' '309xx' '796xx'
 '264xx' '187xx' '250xx' '470xx' '918xx' '418xx' '246xx' '679xx' '247xx'
 '617xx' '843xx' '263xx' '960xx' '651xx' '566xx' '716xx' '466xx' '196xx'
 '447xx' '050xx' '590xx' '365xx' '582xx' '412xx' '594xx' '614xx' '811xx'
 '820xx' '403xx' '822xx' '479xx' '056xx' '404xx' '304xx' '755xx' '635xx'
 '602xx' '827xx' '497xx' '443xx' '075xx' '137xx' '363xx' '041xx' '091xx'
 '653xx' '654xx' '831xx' '556xx' '016xx' '879xx' '588xx' '252xx' '185xx'
 '832xx' '134xx' '607xx' '846xx' '911xx' '735xx' '650xx' '777xx' '683xx'
 '253xx' '258xx' '744xx' '644xx' '289xx' '808xx' '478xx' '647xx' '623xx'
 '318xx' '575xx' '143xx' '178xx' '214xx' '157xx' '397xx' '477xx' '684xx'
 '567xx' '248xx' '963xx' '116xx' '266xx' '169xx' '542xx' '841xx' '813xx'
 '979xx' '961xx' '673xx' '603xx' '828xx' '573xx' '826xx' '449xx' '669xx'
 '593xx' '688xx' '587xx' '167xx' '162xx' '689xx' '084xx' '139xx' '998xx'
 '823xx' '415xx' '048xx' '355xx' '181xx' '710xx' '149xx' '883xx' '729xx'
 '583xx' '893xx' '634xx' '164xx' '426xx' '816xx' '364xx' '316xx' '259xx'
 '743xx' '047xx' '687xx' '256xx' '690xx' '572xx' '538xx' '718xx' '584xx'
 '239xx' '639xx' '664xx' '045xx' '202xx' '686xx' '051xx' '215xx' '739xx'
 '565xx' '036xx' '999xx' '387xx' '736xx' '262xx' '753xx' '569xx' '416xx'
 '772xx' '425xx' '409xx' '369xx' '094xx' '877xx' '406xx' '747xx' '414xx'
 '830xx' '845xx' '059xx' '835xx' '878xx' '332xx' '096xx' '965xx' '861xx'
 '962xx' '692xx' '268xx' '311xx' '090xx' '994xx' '204xx' '408xx' '576xx'
 '896xx']
addr_state : ['VA' 'CA' 'TX' 'ND' 'MD' 'OH' 'GA' 'MT' 'NH' 'NY' 'NC' 'NJ' 'FL' 'OR'
 'NE' 'AL' 'AZ' 'CO' 'TN' 'HI' 'PA' 'MO' 'NV' 'IL' 'AR' 'VT' 'CT' 'MI'
 'WA' 'WI' 'MN' 'MA' 'KS' 'MS' 'NM' 'OK' 'KY' 'LA' 'SC' 'ME' 'IN' 'WY'
 'DE' 'WV' 'AK' 'SD' 'UT' 'DC' 'RI' 'ID']
earliest_cr_line : ['Jul-2005' 'Aug-2002' 'Apr-2009' 'May-1995' 'Dec-2005' 'Nov-2010'
 'Sep-2007' 'Apr-1990' 'Mar-2012' 'May-2001' 'Jan-2006' 'Apr-2014'
 'Mar-2001' 'Mar-2004' 'Jul-1974' 'Nov-1996' 'Aug-2012' 'Feb-2012'
 'Sep-2009' 'Jun-2009' 'Sep-2003' 'Aug-1996' 'Apr-2003' 'Feb-2008'
 'Nov-1980' 'Nov-2014' 'Jan-2003' 'Nov-2007' 'Nov-1993' 'Dec-1994'
 'Feb-1993' 'Dec-2011' 'May-1983' 'Aug-2005' 'Aug-2006' 'Jul-2004'
 'Jan-2004' 'Jun-2011' 'Feb-2003' 'Jul-2003' 'Nov-2003' 'Jun-1992'
 'Oct-1998' 'Jan-2001' 'Feb-2014' 'Feb-2013' 'Aug-1999' 'Nov-1972'
 'Mar-2010' 'Jan-2013' 'May-1994' 'Nov-1999' 'Aug-2010' 'Nov-2005'
 'Jun-2008' 'Nov-2009' 'Nov-1995' 'Jan-1992' 'Aug-1997' 'Sep-2011'
 'Oct-1989' 'May-1998' 'Sep-1997' 'Jul-1993' 'Sep-2005' 'Jan-2007'
 'Mar-1992' 'Oct-1983' 'Apr-2015' 'Aug-2004' 'Feb-2007' 'Jul-2007'
 'Aug-2014' 'Dec-2004' 'Jan-1995' 'Jun-2005' 'Mar-1984' 'Jun-2004'
 'Jan-2000' 'Oct-1990' 'Mar-2006' 'Jun-2000' 'May-2007' 'Nov-1974'
 'Jun-1990' 'Mar-1990' 'Jun-1991' 'Feb-2005' 'Feb-1999' 'Dec-1997'
 'Jan-1997' 'Aug-2008' 'Aug-2007' 'Sep-1993' 'Feb-1986' 'Sep-2002'
 'Sep-2010' 'Nov-2011' 'Mar-2005' 'May-2000' 'Feb-1995' 'Oct-1995'
 'Aug-2003' 'Oct-2007' 'Dec-2012' 'Apr-2005' 'Jun-2002' 'Aug-2000'
 'Feb-2002' 'Nov-1983' 'May-1992' 'Dec-2008' 'Mar-2011' 'Mar-1997'
 'Jan-1985' 'May-2009' 'Jul-1999' 'Nov-2000' 'Oct-2013' 'Nov-1997'
 'May-2010' 'Dec-2010' 'Jul-2015' 'Oct-1997' 'Nov-2004' 'Mar-2013'
 'Feb-2011' 'Nov-2008' 'Feb-1978' 'May-2003' 'Jul-2014' 'Sep-2013'
 'Sep-2006' 'Apr-1999' 'Dec-2007' 'Jul-1994' 'Oct-2002' 'Oct-2006'
 'Jul-2008' 'Feb-2006' 'Aug-2011' 'Nov-1994' 'Oct-2004' 'Jul-1978'
 'Aug-1981' 'Apr-2012' 'Jul-2006' 'Jul-2011' 'Apr-2006' 'Jun-2001'
 'Jan-1996' 'Apr-2013' 'Oct-2008' 'May-1989' 'May-1993' 'Apr-2004'
 'Mar-2009' 'Sep-2000' 'Dec-2002' 'Feb-2015' 'Feb-1998' 'Nov-1991'
 'Jun-2003' 'Nov-2002' 'Apr-1984' 'Mar-2008' 'Jun-1989' 'Jan-2009'
 'Oct-2014' 'Sep-2001' 'Nov-1992' 'Apr-2002' 'Sep-1994' 'Jun-1995'
 'Jun-2013' 'Jul-2009' 'Jul-2010' 'Feb-2004' 'Feb-1996' 'Apr-1983'
 'Sep-2004' 'Dec-1991' 'Sep-2014' 'Feb-2009' 'Nov-2001' 'Jan-2010'
 'Mar-2003' 'Jan-2014' 'Oct-2015' 'May-2014' 'Nov-2006' 'Jun-2007'
 'Jan-2008' 'Dec-2014' 'Apr-2001' 'May-2011' 'Dec-2003' 'Jul-2013'
 'Jul-1984' 'Jul-1995' 'Apr-1976' 'Aug-1990' 'Aug-2013' 'Jul-1996'
 'Sep-2015' 'Sep-1999' 'Sep-1998' 'Dec-2006' 'Jul-1997' 'Dec-1999'
 'Oct-2010' 'Nov-1985' 'Jun-2006' 'Apr-2008' 'Apr-2010' 'Mar-2007'
 'Sep-1991' 'Mar-2015' 'May-1997' 'Apr-1993' 'May-1984' 'Oct-2012'
 'Jan-1990' 'Dec-1996' 'Feb-1990' 'Mar-1993' 'Dec-1998' 'Mar-1985'
 'Jul-2000' 'Jan-2005' 'Oct-2005' 'Apr-2007' 'Apr-1987' 'Apr-1997'
 'May-2005' 'May-2012' 'Sep-2008' 'Oct-1991' 'Apr-2000' 'Jan-2012'
 'Jan-2015' 'May-2004' 'Jan-1984' 'Sep-2012' 'May-1999' 'Jul-1989'
 'Jun-1988' 'Jan-1999' 'Aug-2009' 'Feb-1994' 'Nov-2012' 'Dec-1995'
 'Oct-2003' 'Oct-1994' 'Jun-1982' 'Jun-1998' 'Aug-1992' 'Jun-1985'
 'Jun-2010' 'May-2006' 'Feb-2010' 'Oct-1999' 'Dec-2000' 'Mar-1998'
 'Dec-1988' 'Feb-2000' 'Jun-1997' 'Oct-1993' 'Feb-2001' 'Dec-2009'
 'Sep-1976' 'Jan-2002' 'Aug-2001' 'Mar-2002' 'Aug-1993' 'Feb-1992'
 'Jun-1993' 'Mar-1983' 'Mar-1994' 'Mar-1995' 'Sep-1995' 'Jun-2012'
 'Jul-2002' 'Apr-1995' 'Oct-1987' 'Mar-1973' 'Jun-1986' 'Apr-1988'
 'Jan-1987' 'Feb-1989' 'Aug-2015' 'Nov-2013' 'Aug-1980' 'Aug-1998'
 'Jul-2001' 'Oct-1996' 'Apr-1991' 'Nov-1976' 'May-2002' 'Jul-2012'
 'Jul-1992' 'Jul-1969' 'Jun-1999' 'Sep-1987' 'Apr-1992' 'Jan-2016'
 'May-2013' 'Dec-2013' 'Oct-2000' 'Jul-1988' 'Nov-1998' 'Jul-1990'
 'Nov-2015' 'Apr-1979' 'Sep-1992' 'Dec-2001' 'Jan-2011' 'Jul-1986'
 'Mar-1979' 'Jan-1965' 'Dec-1985' 'Sep-1985' 'Jan-1982' 'Aug-1995'
 'Jun-2014' 'May-2008' 'Apr-2011' 'Dec-1992' 'Oct-1988' 'Aug-1994'
 'Jun-1996' 'Sep-1969' 'Jul-1998' 'Mar-2000' 'Mar-1989' 'Oct-2001'
 'Dec-1993' 'Sep-1996' 'Mar-1991' 'Mar-1987' 'Feb-1991' 'Oct-1979'
 'Apr-1975' 'Dec-1976' 'Dec-2015' 'Aug-1988' 'Feb-1988' 'Feb-1997'
 'Jan-1998' 'May-1996' 'Mar-2014' 'Aug-1989' 'Sep-1984' 'Jul-1982'
 'Dec-1990' 'Jan-1991' 'Aug-1984' 'Apr-1986' 'May-1990' 'Sep-1989'
 'May-1988' 'Nov-1978' 'Nov-1973' 'Jun-2015' 'May-1987' 'Jan-1989'
 'Sep-1988' 'Nov-1979' 'Jan-1988' 'Mar-1999' 'Sep-1964' 'May-1977'
 'Aug-1974' 'Oct-1981' 'Feb-1982' 'Aug-1983' 'Feb-1987' 'Apr-1998'
 'Jul-1991' 'Jun-1994' 'May-1986' 'Dec-1989' 'Dec-1986' 'Aug-1975'
 'Jan-1983' 'Sep-1990' 'Oct-1980' 'Nov-1984' 'Apr-1981' 'Oct-2009'
 'Mar-1976' 'Mar-1996' 'Apr-1996' 'Aug-1964' 'Jan-1975' 'Mar-1988'
 'Feb-1984' 'Oct-2011' 'Nov-1989' 'Aug-1986' 'Jun-1964' 'Dec-1983'
 'Jun-1987' 'Feb-1977' 'May-1985' 'Jul-1981' 'Nov-1988' 'May-1982'
 'Feb-1981' 'Oct-1992' 'Apr-1978' 'May-2015' 'Oct-1985' 'Nov-1986'
 'Jan-1994' 'Apr-1994' 'Aug-1972' 'May-1991' 'Feb-1980' 'Oct-1986'
 'Oct-1982' 'Mar-1978' 'Sep-1983' 'Dec-1987' 'Nov-1967' 'May-1978'
 'Feb-1985' 'Feb-1979' 'Dec-1973' 'Sep-1980' 'Apr-1982' 'Jan-1986'
 'Dec-1977' 'Feb-1961' 'Nov-1990' 'Aug-1985' 'Aug-1982' 'Oct-1978'
 'Aug-1971' 'Sep-1982' 'Sep-1986' 'Dec-1979' 'Dec-1982' 'Jul-1973'
 'Jan-1993' 'Apr-1989' 'Aug-1978' 'Nov-1977' 'Nov-1981' 'Nov-1987'
 'Aug-1991' 'Aug-1987' 'Apr-1985' 'Mar-1977' 'Dec-1980' 'Sep-1978'
 'Apr-1977' 'Apr-1974' 'Jun-1983' 'Aug-1979' 'Oct-1964' 'Mar-1986'
 'Jun-1976' 'Jun-1972' 'Jan-1981' 'Mar-1969' 'Nov-1982' 'Jun-1984'
 'Oct-1984' 'Mar-1981' 'Jan-1979' 'Dec-1965' 'Feb-2016' 'Jun-1979'
 'Jan-1960' 'Jun-1970' 'Dec-1984' 'Sep-1977' 'Feb-1983' 'Jan-1976'
 'Jul-1983' 'Jul-1987' 'Mar-1974' 'Mar-1980' 'Jul-1985' 'May-1976'
 'Oct-1968' 'May-1973' 'Dec-1959' 'Sep-1981' 'Jan-1968' 'Jan-1972'
 'Jul-1980' 'May-1980' 'Nov-1968' 'May-1981' 'Jun-1978' 'Jul-1972'
 'Jun-1977' 'Apr-1973' 'Apr-1970' 'Jan-1944' 'Jun-1980' 'Sep-1972'
 'Jul-1975' 'Mar-1982' 'Sep-1965' 'Mar-1966' 'Apr-1957' 'Jul-1979'
 'Jun-1961' 'Sep-1979' 'May-1966' 'Oct-1976' 'Oct-1973' 'Apr-1969'
 'Feb-1976' 'Jan-1970' 'Jun-1975' 'May-1975' 'Dec-1981' 'Dec-1974'
 'Apr-1980' 'Jul-1968' 'May-1979' 'Jun-1971' 'May-1970' 'Jul-1977'
 'Mar-1975' 'Apr-1972' 'Feb-1975' 'Mar-1968' 'Aug-1966' 'Aug-1976'
 'Jan-1980' 'May-1967' 'Jan-1978' 'Oct-1977' 'Dec-1972' 'Dec-1975'
 'Sep-1966' 'May-1963' 'Jul-1959' 'May-1971' 'Oct-1974' 'Nov-1969'
 'Aug-1967' 'Jun-1967' 'Feb-1967' 'Aug-1968' 'Jan-1977' 'Aug-1977'
 'Jan-1973' 'Jun-1974' 'Sep-1974' 'Oct-1958' 'Feb-1974' 'Jun-1969'
 'Oct-1969' 'Jul-1964' 'Jan-1967' 'Jul-1976' 'Sep-1975' 'Sep-1968'
 'Aug-1965' 'Oct-1971' 'Dec-1978' 'Feb-1973' 'Nov-1959' 'Jun-1981'
 'Oct-1975' 'Jan-1974' 'Jan-1963' 'Aug-1973' 'Apr-1971' 'Sep-1973'
 'May-1974' 'Oct-1966' 'Jan-1969' 'Nov-1975' 'Nov-1971' 'Dec-1969'
 'Jul-1970' 'Aug-1969' 'Jun-1968' 'Mar-1970' 'Oct-1970' 'Feb-1970'
 'May-1962' 'Feb-1971' 'May-1972' 'Sep-1961' 'Feb-1972' 'Aug-1970'
 'Oct-1956' 'Apr-1968' 'Jun-1965' 'Oct-1972' 'Feb-1965' 'Jul-1965'
 'Nov-1962' 'Dec-1960' 'Jul-1967' 'Sep-1970' 'Jun-1966' 'Nov-1965'
 'Jan-1961' 'Jul-1971' 'Dec-1962' 'Dec-1970' 'Feb-1968' 'Jul-1961'
 'Sep-1967' 'Feb-1969' 'Dec-1971' 'Apr-1966' 'Jan-1971' 'May-1969'
 'Mar-1971' 'Dec-1964' 'Jan-1955' 'Jun-1973' 'Sep-1971' 'Mar-1972'
 'Apr-1964' 'Nov-1960' 'Jan-1959' 'Nov-1966' 'May-1961' 'Dec-1968'
 'Feb-1966' 'Jan-1951' 'Apr-1967' 'Jan-1964' 'Mar-1967' 'Jul-1960'
 'Jan-1966' 'Apr-1965' 'Jan-1962' 'Nov-1970' 'Apr-1963' 'Mar-1960'
 'Sep-1959' 'Mar-1963' 'Feb-1959' 'May-1965' 'Aug-1963' 'Mar-1959']
revol_util : ['66.7%' '95.6%' '43.5%' ... '107.4%' '103.5%' '105.5%']
initial_list_status : ['w' 'f']
last_pymnt_d : ['Apr-2019' 'Mar-2019' 'Feb-2019' 'Jan-2019']
next_pymnt_d : ['May-2019' 'Apr-2019']
last_credit_pull_d : ['Apr-2019' 'Mar-2019' 'Feb-2019' 'Jan-2019' 'Dec-2018']
application_type : ['Individual' 'Joint App']
verification_status_joint : ['Not Verified' 'Verified' 'Source Verified']
sec_app_earliest_cr_line : ['Aug-2006' 'Aug-2004' 'Jan-2003' 'Sep-2011' 'Jan-2012' 'Nov-2006'
 'Jun-2005' 'Aug-1975' 'Nov-2008' 'Jul-2009' 'Apr-2006' 'Aug-2007'
 'Jan-2000' 'Apr-1989' 'Nov-2007' 'May-2009' 'Nov-2001' 'Dec-2005'
 'Nov-1999' 'Jul-2015' 'Apr-2004' 'Dec-2004' 'Aug-2005' 'Oct-2010'
 'Oct-2004' 'May-1995' 'Jun-2008' 'Jan-1996' 'Nov-2002' 'Nov-2003'
 'Sep-2006' 'Mar-2004' 'Aug-2009' 'Sep-2009' 'Jun-2013' 'May-2012'
 'Mar-2009' 'Nov-1997' 'Aug-2001' 'Dec-1992' 'May-2000' 'Jul-2003'
 'Apr-2007' 'Jul-2007' 'Mar-2016' 'Sep-2000' 'Jul-2000' 'Aug-2002'
 'Jun-2014' 'Sep-1991' 'Mar-1999' 'Feb-2001' 'Dec-1998' 'Dec-1990'
 'May-2018' 'Sep-2005' 'Jan-2010' 'Oct-2006' 'Oct-2011' 'Mar-2002'
 'Feb-2015' 'Mar-2018' 'Aug-2013' 'Jun-1982' 'Aug-1994' 'Jan-2008'
 'Jul-1989' 'Mar-2012' 'Jan-2007' 'May-1990' 'Oct-1988' 'Nov-2005'
 'Sep-2002' 'Mar-2003' 'Aug-2017' 'Sep-2012' 'Jun-2004' 'Jan-2013'
 'Aug-2008' 'Nov-2000' 'Feb-2012' 'Jun-2003' 'Jun-1995' 'Jan-2014'
 'Jul-2008' 'Jul-1997' 'Mar-2006' 'Dec-2003' 'Jul-2004' 'Apr-2001'
 'Apr-2014' 'Jun-2009' 'Jun-2001' 'Jun-1996' 'Aug-1990' 'Dec-2010'
 'Sep-2008' 'Apr-1996' 'Aug-2000' 'Jul-2005' 'Apr-1999' 'Feb-2007'
 'Jun-2006' 'Jul-2014' 'Sep-2004' 'Aug-1996' 'Apr-2011' 'Jan-2002'
 'Oct-2008' 'Feb-2000' 'Dec-2014' 'Apr-2008' 'Oct-2003' 'Sep-2007'
 'May-2007' 'Jun-1987' 'May-2003' 'Nov-1990' 'Feb-2010' 'Dec-1996'
 'May-1991' 'Dec-2009' 'Sep-1998' 'Oct-1999' 'Jun-2007' 'Jan-2006'
 'Feb-2002' 'Feb-2014' 'Dec-2007' 'May-2015' 'Aug-2003' 'May-1979'
 'Jul-1996' 'Oct-2012' 'Feb-2005' 'Aug-2011' 'Apr-2000' 'Aug-1984'
 'Jul-2010' 'Dec-2013' 'Apr-1994' 'Dec-2015' 'Jul-2013' 'Oct-2000'
 'Jun-1999' 'Dec-2006' 'Mar-2007' 'Mar-2014' 'Aug-1995' 'Feb-2013'
 'May-1970' 'Jun-2010' 'Sep-1988' 'Oct-1997' 'Apr-2003' 'Feb-2004'
 'Mar-2008' 'Mar-1998' 'Feb-1995' 'Dec-2002' 'May-1998' 'Mar-1995'
 'Jul-2011' 'Mar-1997' 'Aug-2016' 'May-2004' 'Jun-1994' 'Apr-2013'
 'Apr-1998' 'Apr-2005' 'Sep-2015' 'Jul-2006' 'May-2013' 'May-2005'
 'Aug-2012' 'Nov-1995' 'Sep-1997' 'Jul-1993' 'Nov-2004' 'Oct-1996'
 'May-2006' 'May-2016' 'Nov-1989' 'Nov-1998' 'Mar-2000' 'Mar-2015'
 'Nov-2012' 'Nov-2010' 'Dec-2001' 'Jun-2002' 'Jan-1998' 'Oct-2002'
 'Dec-1999' 'Sep-2001' 'Oct-1998' 'Jun-1998' 'Jun-2000' 'Sep-2013'
 'Apr-2010' 'Dec-1993' 'Aug-1989' 'Feb-1991' 'Sep-2003' 'Aug-1998'
 'Nov-1991' 'Feb-1998' 'Mar-2005' 'Oct-2005' 'Oct-2007' 'Nov-1986'
 'Mar-2001' 'Mar-1988' 'Sep-1999' 'Oct-1993' 'Jul-2001' 'Jan-1986'
 'Dec-2000' 'Jul-1998' 'Oct-2015' 'Feb-2009' 'Oct-2009' 'Apr-1990'
 'Jun-1997' 'Nov-2014' 'Aug-2014' 'Dec-2012' 'Nov-1978' 'Jan-1991'
 'Nov-1985' 'Feb-2003' 'May-1982' 'Apr-2009' 'May-1994' 'Jan-2001'
 'Apr-2015' 'Sep-1995' 'Mar-1994' 'Jan-2005' 'Sep-1996' 'May-1999'
 'Jan-2009' 'Mar-2013' 'Oct-2001' 'Sep-1992' 'Feb-2011' 'Dec-1986'
 'Jan-1997' 'Jun-1992' 'Aug-1987' 'Oct-1983' 'Jan-1985' 'Feb-2006'
 'Nov-2009' 'Feb-1999' 'Feb-2008' 'Oct-1994' 'Feb-1990' 'Dec-1984'
 'Apr-2002' 'Jul-2016' 'Dec-2008' 'Dec-1988' 'May-1997' 'Jan-2004'
 'Dec-1997' 'Mar-1987' 'Jun-1988' 'Aug-1991' 'May-1989' 'Aug-1999'
 'Oct-1995' 'Nov-1993' 'Aug-1988' 'Oct-1981' 'Nov-1971' 'Apr-1997'
 'Nov-1996' 'Oct-1991' 'Mar-2011' 'Dec-1978' 'Sep-2010' 'May-1996'
 'Nov-2011' 'Mar-1991' 'Sep-1993' 'Apr-1987' 'Dec-1991' 'Dec-2011'
 'Mar-1989' 'May-2017' 'Aug-1997' 'Mar-1981' 'May-2008' 'Oct-1989'
 'Oct-2014' 'Feb-1996' 'Nov-1981' 'Jun-1989' 'Jul-2002' 'May-1992'
 'Apr-1991' 'Oct-1980' 'Jan-1987' 'Jun-2011' 'Jan-1990' 'Aug-2015'
 'May-1993' 'Sep-1994' 'Jan-2017' 'Jan-1999' 'Aug-1985' 'Nov-2015'
 'Apr-2012' 'Jul-1988' 'May-1978' 'Nov-1976' 'Oct-2013' 'Feb-1986'
 'Feb-2018' 'Feb-1997' 'Nov-1974' 'Mar-1993' 'Jul-1999' 'Jan-1968'
 'Dec-1982' 'Feb-1994' 'Feb-1989' 'Mar-1984' 'Feb-2016' 'Jul-2012'

In [ ]:
# Importing the necessary library
from sklearn.preprocessing import OneHotEncoder

# Creating an instance of OneHotEncoder
encoder = OneHotEncoder()

# Fit and transform the categorical columns
df_cat= encoder.fit_transform(df[categorical_cols])

# Convert the encoded categorical columns to a DataFrame
df_cat = pd.DataFrame(df_cat.toarray(), columns=encoder.get_feature_names_out(categorical_cols))
# Concatenate with the original DataFrame
df_encoded = pd.concat([df[numerical_cols], df_cat], axis=1)

NameError: name 'df' is not defined